/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package showdowntotrainer;

import java.util.ArrayList;

/**
 *
 * @author codem
 */
public class AbilityPairs {
    public static ArrayList<Pair> List = new ArrayList<>();
    
    public void setup()
    {
        List.add(new Pair("STENCH", "Stench"));
        List.add(new Pair("DRIZZLE", "Drizzle"));
        List.add(new Pair("SPEEDBOOST", "Speed Boost"));
        List.add(new Pair("BATTLEARMOR", "Battle Armor"));
        List.add(new Pair("STURDY", "Sturdy"));
        List.add(new Pair("DAMP", "Damp"));
        List.add(new Pair("LIMBER", "Limber"));
        List.add(new Pair("SANDVEIL", "Sand Veil"));
        List.add(new Pair("STATIC", "Static"));
        List.add(new Pair("VOLTABSORB", "Volt Absorb"));
        List.add(new Pair("WATERABSORB", "Water Absorb"));
        List.add(new Pair("OBLIVIOUS", "Oblivious"));
        List.add(new Pair("CLOUDNINE", "Cloud Nine"));
        List.add(new Pair("COMPOUNDEYES", "Compound Eyes"));
        List.add(new Pair("INSOMNIA", "Insomnia"));
        List.add(new Pair("COLORCHANGE", "Color Change"));
        List.add(new Pair("IMMUNITY", "Immunity"));
        List.add(new Pair("FLASHFIRE", "Flash Fire"));
        List.add(new Pair("SHIELDDUST", "Shield Dust"));
        List.add(new Pair("OWNTEMPO", "Own Tempo"));
        List.add(new Pair("SUCTIONCUPS", "Suction Cups"));
        List.add(new Pair("INTIMIDATE", "Intimidate"));
        List.add(new Pair("SHADOWTAG", "Shadow Tag"));
        List.add(new Pair("ROUGHSKIN", "Rough Skin"));
        List.add(new Pair("WONDERGUARD", "Wonder Guard"));
        List.add(new Pair("LEVITATE", "Levitate"));
        List.add(new Pair("EFFECTSPORE", "Effect Spore"));
        List.add(new Pair("SYNCHRONIZE", "Synchronize"));
        List.add(new Pair("CLEARBODY", "Clear Body"));
        List.add(new Pair("NATURALCURE", "Natural Cure"));
        List.add(new Pair("LIGHTNINGROD", "Lightning Rod"));
        List.add(new Pair("SERENEGRACE", "Serene Grace"));
        List.add(new Pair("SWIFTSWIM", "Swift Swim"));
        List.add(new Pair("CHLOROPHYLL", "Chlorophyll"));
        List.add(new Pair("ILLUMINATE", "Illuminate"));
        List.add(new Pair("TRACE", "Trace"));
        List.add(new Pair("HUGEPOWER", "Huge Power"));
        List.add(new Pair("POISONPOINT", "Poison Point"));
        List.add(new Pair("INNERFOCUS", "Inner Focus"));
        List.add(new Pair("MAGMAARMOR", "Magma Armor"));
        List.add(new Pair("WATERVEIL", "Water Veil"));
        List.add(new Pair("MAGNETPULL", "Magnet Pull"));
        List.add(new Pair("SOUNDPROOF", "Soundproof"));
        List.add(new Pair("RAINDISH", "Rain Dish"));
        List.add(new Pair("SANDSTREAM", "Sand Stream"));
        List.add(new Pair("PRESSURE", "Pressure"));
        List.add(new Pair("THICKFAT", "Thick Fat"));
        List.add(new Pair("EARLYBIRD", "Early Bird"));
        List.add(new Pair("FLAMEBODY", "Flame Body"));
        List.add(new Pair("RUNAWAY", "Run Away"));
        List.add(new Pair("KEENEYE", "Keen Eye"));
        List.add(new Pair("HYPERCUTTER", "Hyper Cutter"));
        List.add(new Pair("PICKUP", "Pickup"));
        List.add(new Pair("TRUANT", "Truant"));
        List.add(new Pair("HUSTLE", "Hustle"));
        List.add(new Pair("CUTECHARM", "Cute Charm"));
        List.add(new Pair("PLUS", "Plus"));
        List.add(new Pair("MINUS", "Minus"));
        List.add(new Pair("FORECAST", "Forecast"));
        List.add(new Pair("STICKYHOLD", "Sticky Hold"));
        List.add(new Pair("SHEDSKIN", "Shed Skin"));
        List.add(new Pair("GUTS", "Guts"));
        List.add(new Pair("MARVELSCALE", "Marvel Scale"));
        List.add(new Pair("LIQUIDOOZE", "Liquid Ooze"));
        List.add(new Pair("OVERGROW", "Overgrow"));
        List.add(new Pair("BLAZE", "Blaze"));
        List.add(new Pair("TORRENT", "Torrent"));
        List.add(new Pair("SWARM", "Swarm"));
        List.add(new Pair("ROCKHEAD", "Rock Head"));
        List.add(new Pair("DROUGHT", "Drought"));
        List.add(new Pair("ARENATRAP", "Arena Trap"));
        List.add(new Pair("VITALSPIRIT", "Vital Spirit"));
        List.add(new Pair("WHITESMOKE", "White Smoke"));
        List.add(new Pair("PUREPOWER", "Pure Power"));
        List.add(new Pair("SHELLARMOR", "Shell Armor"));
        List.add(new Pair("AIRLOCK", "Air Lock"));
        List.add(new Pair("TANGLEDFEET", "Tangled Feet"));
        List.add(new Pair("MOTORDRIVE", "Motor Drive"));
        List.add(new Pair("RIVALRY", "Rivalry"));
        List.add(new Pair("STEADFAST", "Steadfast"));
        List.add(new Pair("SNOWCLOAK", "Snow Cloak"));
        List.add(new Pair("GLUTTONY", "Gluttony"));
        List.add(new Pair("ANGERPOINT", "Anger Point"));
        List.add(new Pair("UNBURDEN", "Unburden"));
        List.add(new Pair("HEATPROOF", "Heatproof"));
        List.add(new Pair("SIMPLE", "Simple"));
        List.add(new Pair("DRYSKIN", "Dry Skin"));
        List.add(new Pair("DOWNLOAD", "Download"));
        List.add(new Pair("IRONFIST", "Iron Fist"));
        List.add(new Pair("POISONHEAL", "Poison Heal"));
        List.add(new Pair("ADAPTABILITY", "Adaptability"));
        List.add(new Pair("SKILLLINK", "Skill Link"));
        List.add(new Pair("HYDRATION", "Hydration"));
        List.add(new Pair("SOLARPOWER", "Solar Power"));
        List.add(new Pair("QUICKFEET", "Quick Feet"));
        List.add(new Pair("NORMALIZE", "Normalize"));
        List.add(new Pair("SNIPER", "Sniper"));
        List.add(new Pair("MAGICGUARD", "Magic Guard"));
        List.add(new Pair("NOGUARD", "No Guard"));
        List.add(new Pair("STALL", "Stall"));
        List.add(new Pair("TECHNICIAN", "Technician"));
        List.add(new Pair("LEAFGUARD", "Leaf Guard"));
        List.add(new Pair("KLUTZ", "Klutz"));
        List.add(new Pair("MOLDBREAKER", "Mold Breaker"));
        List.add(new Pair("SUPERLUCK", "Super Luck"));
        List.add(new Pair("AFTERMATH", "Aftermath"));
        List.add(new Pair("ANTICIPATION", "Anticipation"));
        List.add(new Pair("FOREWARN", "Forewarn"));
        List.add(new Pair("UNAWARE", "Unaware"));
        List.add(new Pair("TINTEDLENS", "Tinted Lens"));
        List.add(new Pair("FILTER", "Filter"));
        List.add(new Pair("SLOWSTART", "Slow Start"));
        List.add(new Pair("SCRAPPY", "Scrappy"));
        List.add(new Pair("STORMDRAIN", "Storm Drain"));
        List.add(new Pair("ICEBODY", "Ice Body"));
        List.add(new Pair("SOLIDROCK", "Solid Rock"));
        List.add(new Pair("SNOWWARNING", "Snow Warning"));
        List.add(new Pair("HONEYGATHER", "Honey Gather"));
        List.add(new Pair("FRISK", "Frisk"));
        List.add(new Pair("RECKLESS", "Reckless"));
        List.add(new Pair("MULTITYPE", "Multitype"));
        List.add(new Pair("FLOWERGIFT", "Flower Gift"));
        List.add(new Pair("BADDREAMS", "Bad Dreams"));
        List.add(new Pair("PICKPOCKET", "Pickpocket"));
        List.add(new Pair("SHEERFORCE", "Sheer Force"));
        List.add(new Pair("CONTRARY", "Contrary"));
        List.add(new Pair("UNNERVE", "Unnerve"));
        List.add(new Pair("DEFIANT", "Defiant"));
        List.add(new Pair("DEFEATIST", "Defeatist"));
        List.add(new Pair("CURSEDBODY", "Cursed Body"));
        List.add(new Pair("HEALER", "Healer"));
        List.add(new Pair("FRIENDGUARD", "Friend Guard"));
        List.add(new Pair("WEAKARMOR", "Weak Armor"));
        List.add(new Pair("HEAVYMETAL", "Heavy Metal"));
        List.add(new Pair("LIGHTMETAL", "Light Metal"));
        List.add(new Pair("MULTISCALE", "Multiscale"));
        List.add(new Pair("TOXICBOOST", "Toxic Boost"));
        List.add(new Pair("FLAREBOOST", "Flare Boost"));
        List.add(new Pair("HARVEST", "Harvest"));
        List.add(new Pair("TELEPATHY", "Telepathy"));
        List.add(new Pair("MOODY", "Moody"));
        List.add(new Pair("OVERCOAT", "Overcoat"));
        List.add(new Pair("POISONTOUCH", "Poison Touch"));
        List.add(new Pair("REGENERATOR", "Regenerator"));
        List.add(new Pair("BIGPECKS", "Big Pecks"));
        List.add(new Pair("SANDRUSH", "Sand Rush"));
        List.add(new Pair("WONDERSKIN", "Wonder Skin"));
        List.add(new Pair("ANALYTIC", "Analytic"));
        List.add(new Pair("ILLUSION", "Illusion"));
        List.add(new Pair("IMPOSTER", "Imposter"));
        List.add(new Pair("INFILTRATOR", "Infiltrator"));
        List.add(new Pair("MUMMY", "Mummy"));
        List.add(new Pair("MOXIE", "Moxie"));
        List.add(new Pair("JUSTIFIED", "Justified"));
        List.add(new Pair("RATTLED", "Rattled"));
        List.add(new Pair("MAGICBOUNCE", "Magic Bounce"));
        List.add(new Pair("SAPSIPPER", "Sap Sipper"));
        List.add(new Pair("PRANKSTER", "Prankster"));
        List.add(new Pair("SANDFORCE", "Sand Force"));
        List.add(new Pair("IRONBARBS", "Iron Barbs"));
        List.add(new Pair("ZENMODE", "Zen Mode"));
        List.add(new Pair("VICTORYSTAR", "Victory Star"));
        List.add(new Pair("TURBOBLAZE", "Turboblaze"));
        List.add(new Pair("TERAVOLT", "Teravolt"));
        List.add(new Pair("AROMAVEIL", "Aroma Veil"));
        List.add(new Pair("FLOWERVEIL", "Flower Veil"));
        List.add(new Pair("CHEEKPOUCH", "Cheek Pouch"));
        List.add(new Pair("PROTEAN", "Protean"));
        List.add(new Pair("FURCOAT", "Fur Coat"));
        List.add(new Pair("MAGICIAN", "Magician"));
        List.add(new Pair("BULLETPROOF", "Bulletproof"));
        List.add(new Pair("COMPETITIVE", "Competitive"));
        List.add(new Pair("STRONGJAW", "Strong Jaw"));
        List.add(new Pair("REFRIGERATE", "Refrigerate"));
        List.add(new Pair("SWEETVEIL", "Sweet Veil"));
        List.add(new Pair("STANCECHANGE", "Stance Change"));
        List.add(new Pair("GALEWINGS", "Gale Wings"));
        List.add(new Pair("MEGALAUNCHER", "Mega Launcher"));
        List.add(new Pair("GRASSPELT", "Grass Pelt"));
        List.add(new Pair("SYMBIOSIS", "Symbiosis"));
        List.add(new Pair("TOUGHCLAWS", "Tough Claws"));
        List.add(new Pair("PIXILATE", "Pixilate"));
        List.add(new Pair("GOOEY", "Gooey"));
        List.add(new Pair("AERILATE", "Aerilate"));
        List.add(new Pair("PARENTALBOND", "Parental Bond"));
        List.add(new Pair("DARKAURA", "Dark Aura"));
        List.add(new Pair("FAIRYAURA", "Fairy Aura"));
        List.add(new Pair("AURABREAK", "Aura Break"));
        List.add(new Pair("PRIMORDIALSEA", "Primordial Sea"));
        List.add(new Pair("DESOLATELAND", "Desolate Land"));
        List.add(new Pair("DELTASTREAM", "Delta Stream"));
        List.add(new Pair("STAMINA", "Stamina"));
        List.add(new Pair("WIMPOUT", "Wimp Out"));
        List.add(new Pair("EMERGENCYEXIT", "Emergency Exit"));
        List.add(new Pair("WATERCOMPACTION", "Water Compaction"));
        List.add(new Pair("MERCILESS", "Merciless"));
        List.add(new Pair("SHIELDSDOWN", "Shields Down"));
        List.add(new Pair("STAKEOUT", "Stakeout"));
        List.add(new Pair("WATERBUBBLE", "Water Bubble"));
        List.add(new Pair("STEELWORKER", "Steelworker"));
        List.add(new Pair("BERSERK", "Berserk"));
        List.add(new Pair("SLUSHRUSH", "Slush Rush"));
        List.add(new Pair("LONGREACH", "Long Reach"));
        List.add(new Pair("LIQUIDVOICE", "Liquid Voice"));
        List.add(new Pair("TRIAGE", "Triage"));
        List.add(new Pair("GALVANIZE", "Galvanize"));
        List.add(new Pair("SURGESURFER", "Surge Surfer"));
        List.add(new Pair("SCHOOLING", "Schooling"));
        List.add(new Pair("DISGUISE", "Disguise"));
        List.add(new Pair("BATTLEBOND", "Battle Bond"));
        List.add(new Pair("POWERCONSTRUCT", "Power Construct"));
        List.add(new Pair("CORROSION", "Corrosion"));
        List.add(new Pair("COMATOSE", "Comatose"));
        List.add(new Pair("QUEENLYMAJESTY", "Queenly Majesty"));
        List.add(new Pair("INNARDSOUT", "Innards Out"));
        List.add(new Pair("DANCER", "Dancer"));
        List.add(new Pair("BATTERY", "Battery"));
        List.add(new Pair("FLUFFY", "Fluffy"));
        List.add(new Pair("DAZZLING", "Dazzling"));
        List.add(new Pair("SOULHEART", "Soul-Heart"));
        List.add(new Pair("TANGLINGHAIR", "Tangling Hair"));
        List.add(new Pair("RECEIVER", "Receiver"));
        List.add(new Pair("POWEROFALCHEMY", "Power of Alchemy"));
        List.add(new Pair("BEASTBOOST", "Beast Boost"));
        List.add(new Pair("RKSSYSTEM", "RKS System"));
        List.add(new Pair("ELECTRICSURGE", "Electric Surge"));
        List.add(new Pair("PSYCHICSURGE", "Psychic Surge"));
        List.add(new Pair("MISTYSURGE", "Misty Surge"));
        List.add(new Pair("GRASSYSURGE", "Grassy Surge"));
        List.add(new Pair("FULLMETALBODY", "Full Metal Body"));
        List.add(new Pair("SHADOWSHIELD", "Shadow Shield"));
        List.add(new Pair("PRISMARMOR", "Prism Armor"));
        List.add(new Pair("NEUROFORCE", "Neuroforce"));
        List.add(new Pair("INTREPIDSWORD", "Intrepid Sword"));
        List.add(new Pair("DAUNTLESSSHIELD", "Dauntless Shield"));
        List.add(new Pair("LIBERO", "Libero"));
        List.add(new Pair("BALLFETCH", "Ball Fetch"));
        List.add(new Pair("COTTONDOWN", "Cotton Down"));
        List.add(new Pair("PROPELLERTAIL", "Propeller Tail"));
        List.add(new Pair("MIRRORARMOR", "Mirror Armor"));
        List.add(new Pair("GULPMISSILE", "Gulp Missile"));
        List.add(new Pair("STALWART", "Stalwart"));
        List.add(new Pair("STEAMENGINE", "Steam Engine"));
        List.add(new Pair("PUNKROCK", "Punk Rock"));
        List.add(new Pair("SANDSPIT", "Sand Spit"));
        List.add(new Pair("ICESCALES", "Ice Scales"));
        List.add(new Pair("RIPEN", "Ripen"));
        List.add(new Pair("ICEFACE", "Ice Face"));
        List.add(new Pair("POWERSPOT", "Power Spot"));
        List.add(new Pair("MIMICRY", "Mimicry"));
        List.add(new Pair("SCREENCLEANER", "Screen Cleaner"));
        List.add(new Pair("STEELYSPIRIT", "Steely Spirit"));
        List.add(new Pair("PERISHBODY", "Perish Body"));
        List.add(new Pair("WANDERINGSPIRIT", "Wandering Spirit"));
        List.add(new Pair("GORILLATACTICS", "Gorilla Tactics"));
        List.add(new Pair("NEUTRALIZINGGAS", "Neutralizing Gas"));
        List.add(new Pair("PASTELVEIL", "Pastel Veil"));
        List.add(new Pair("HUNGERSWITCH", "Hunger Switch"));
        List.add(new Pair("QUICKDRAW", "Quick Draw"));
        List.add(new Pair("UNSEENFIST", "Unseen Fist"));
        List.add(new Pair("CURIOUSMEDICINE", "Curious Medicine"));
        List.add(new Pair("TRANSISTOR", "Transistor"));
        List.add(new Pair("DRAGONSMAW", "Dragon's Maw"));
        List.add(new Pair("CHILLINGNEIGH", "Chilling Neigh"));
        List.add(new Pair("GRIMNEIGH", "Grim Neigh"));
        List.add(new Pair("ASONECHILLINGNEIGH", "As One (Glastrier)"));
        List.add(new Pair("ASONEGRIMNEIGH", "As One (Spectrier)"));
        List.add(new Pair("ANGERSHELL", "Anger Shell"));
        List.add(new Pair("ARMORTAIL", "Armor Tail"));
        List.add(new Pair("BEADSOFRUIN", "Beads of Ruin"));
        List.add(new Pair("COMMANDER", "Commander"));
        List.add(new Pair("COSTAR", "Costar"));
        List.add(new Pair("CUDCHEW", "Cud Chew"));
        List.add(new Pair("EARTHEATER", "Earth Eater"));
        List.add(new Pair("ELECTROMORPHOSIS", "Electromorphosis"));
        List.add(new Pair("GOODASGOLD", "Good as Gold"));
        List.add(new Pair("GUARDDOG", "Guard Dog"));
        List.add(new Pair("HADRONENGINE", "Hadron Engine"));
        List.add(new Pair("LINGERINGAROMA", "Lingering Aroma"));
        List.add(new Pair("MYCELIUMMIGHT", "Mycelium Might"));
        List.add(new Pair("OPPORTUNIST", "Opportunist"));
        List.add(new Pair("ORICHALCUMPULSE", "Orichalcum Pulse"));
        List.add(new Pair("PROTOSYNTHESIS", "Protosynthesis"));
        List.add(new Pair("PURIFYINGSALT", "Purifying Salt"));
        List.add(new Pair("QUARKDRIVE", "Quark Drive"));
        List.add(new Pair("ROCKYPAYLOAD", "Rocky Payload"));
        List.add(new Pair("SEEDSOWER", "Seed Sower"));
        List.add(new Pair("SHARPNESS", "Sharpness"));
        List.add(new Pair("SUPREMEOVERLORD", "Supreme Overlord"));
        List.add(new Pair("SWORDOFRUIN", "Sword of Ruin"));
        List.add(new Pair("TABLETSOFRUIN", "Tablets of Ruin"));
        List.add(new Pair("THERMALEXCHANGE", "Thermal Exchange"));
        List.add(new Pair("TOXICDEBRIS", "Toxic Debris"));
        List.add(new Pair("VESSELOFRUIN", "Vessel of Ruin"));
        List.add(new Pair("WELLBAKEDBODY", "Well-Baked Body"));
        List.add(new Pair("WINDPOWER", "Wind Power"));
        List.add(new Pair("WINDRIDER", "Wind Rider"));
        List.add(new Pair("ZEROTOHERO", "Zero to Hero"));
        List.add(new Pair("SUPERSWEETSYRUP", "Supersweet Syrup"));
        List.add(new Pair("HOSPITALITY", "Hospitality"));
        List.add(new Pair("TOXICCHAIN", "Toxic Chain"));
        List.add(new Pair("MINDSEYE", "Mind's Eye"));
        List.add(new Pair("EMBODYASPECT", "Embody Aspect (Teal)"));
        List.add(new Pair("EMBODYASPECT_1", "Embody Aspect (Wellspring)"));
        List.add(new Pair("EMBODYASPECT_2", "Embody Aspect (Hearthflame)"));
        List.add(new Pair("EMBODYASPECT_3", "Embody Aspect (Cornerstone)"));
        List.add(new Pair("POISONPUPPETEER", "Poison Puppeteer"));
        List.add(new Pair("TERASHIFT", "Tera Shift"));
        List.add(new Pair("TERASHELL", "Tera Shell"));
        List.add(new Pair("TERAFORMZERO", "Teraform Zero"));
    }
}
