/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package showdowntotrainer;

import java.util.ArrayList;

/**
 *
 * @author codem
 */
public class ItemPairs {
    public static ArrayList<Pair> List = new ArrayList<>();
    
    public void setup()
    {
        // Base
        List.add(new Pair("REPEL", "Repel"));
        List.add(new Pair("SUPERREPEL", "Super Repel"));
        List.add(new Pair("MAXREPEL", "Max Repel"));
        List.add(new Pair("BLACKFLUTE", "Black Flute"));
        List.add(new Pair("WHITEFLUTE", "White Flute"));
        List.add(new Pair("HONEY", "Honey"));
        List.add(new Pair("REDSHARD", "Red Shard"));
        List.add(new Pair("YELLOWSHARD", "Yellow Shard"));
        List.add(new Pair("BLUESHARD", "Blue Shard"));
        List.add(new Pair("GREENSHARD", "Green Shard"));
        List.add(new Pair("FIRESTONE", "Fire Stone"));
        List.add(new Pair("THUNDERSTONE", "Thunder Stone"));
        List.add(new Pair("WATERSTONE", "Water Stone"));
        List.add(new Pair("LEAFSTONE", "Leaf Stone"));
        List.add(new Pair("MOONSTONE", "Moon Stone"));
        List.add(new Pair("SUNSTONE", "Sun Stone"));
        List.add(new Pair("DUSKSTONE", "Dusk Stone"));
        List.add(new Pair("DAWNSTONE", "Dawn Stone"));
        List.add(new Pair("SHINYSTONE", "Shiny Stone"));
        List.add(new Pair("ICESTONE", "Ice Stone"));
        List.add(new Pair("SWEETAPPLE", "Sweet Apple"));
        List.add(new Pair("TARTAPPLE", "Tart Apple"));
        List.add(new Pair("CRACKEDPOT", "Cracked Pot"));
        List.add(new Pair("CHIPPEDPOT", "Chipped Pot"));
        List.add(new Pair("GALARICACUFF", "Galarica Cuff"));
        List.add(new Pair("GALARICAWREATH", "Galarica Wreath"));
        List.add(new Pair("REDAPRICORN", "Red Apricorn"));
        List.add(new Pair("YELLOWAPRICORN", "Yellow Apricorn"));
        List.add(new Pair("BLUEAPRICORN", "Blue Apricorn"));
        List.add(new Pair("GREENAPRICORN", "Green Apricorn"));
        List.add(new Pair("PINKAPRICORN", "Pink Apricorn"));
        List.add(new Pair("WHITEAPRICORN", "White Apricorn"));
        List.add(new Pair("BLACKAPRICORN", "Black Apricorn"));
        List.add(new Pair("HELIXFOSSIL", "Helix Fossil"));
        List.add(new Pair("DOMEFOSSIL", "Dome Fossil"));
        List.add(new Pair("OLDAMBER", "Old Amber"));
        List.add(new Pair("ROOTFOSSIL", "Root Fossil"));
        List.add(new Pair("CLAWFOSSIL", "Claw Fossil"));
        List.add(new Pair("SKULLFOSSIL", "Skull Fossil"));
        List.add(new Pair("ARMORFOSSIL", "Armor Fossil"));
        List.add(new Pair("COVERFOSSIL", "Cover Fossil"));
        List.add(new Pair("PLUMEFOSSIL", "Plume Fossil"));
        List.add(new Pair("JAWFOSSIL", "Jaw Fossil"));
        List.add(new Pair("SAILFOSSIL", "Sail Fossil"));
        List.add(new Pair("FOSSILIZEDBIRD", "Fossilized Bird"));
        List.add(new Pair("FOSSILIZEDFISH", "Fossilized Fish"));
        List.add(new Pair("FOSSILIZEDDRAKE", "Fossilized Drake"));
        List.add(new Pair("FOSSILIZEDDINO", "Fossilized Dino"));
        List.add(new Pair("PRETTYFEATHER", "Pretty Feather"));
        List.add(new Pair("TINYMUSHROOM", "Tiny Mushroom"));
        List.add(new Pair("BIGMUSHROOM", "Big Mushroom"));
        List.add(new Pair("BALMMUSHROOM", "Balm Mushroom"));
        List.add(new Pair("PEARL", "Pearl"));
        List.add(new Pair("BIGPEARL", "Big Pearl"));
        List.add(new Pair("PEARLSTRING", "Pearl String"));
        List.add(new Pair("STARDUST", "Stardust"));
        List.add(new Pair("STARPIECE", "Star Piece"));
        List.add(new Pair("COMETSHARD", "Comet Shard"));
        List.add(new Pair("NUGGET", "Nugget"));
        List.add(new Pair("BIGNUGGET", "Big Nugget"));
        List.add(new Pair("HEARTSCALE", "Heart Scale"));
        List.add(new Pair("SLOWPOKETAIL", "Slowpoke Tail"));
        List.add(new Pair("RAREBONE", "Rare Bone"));
        List.add(new Pair("RELICCOPPER", "Relic Copper"));
        List.add(new Pair("RELICSILVER", "Relic Silver"));
        List.add(new Pair("RELICGOLD", "Relic Gold"));
        List.add(new Pair("RELICVASE", "Relic Vase"));
        List.add(new Pair("RELICBAND", "Relic Band"));
        List.add(new Pair("RELICSTATUE", "Relic Statue"));
        List.add(new Pair("RELICCROWN", "Relic Crown"));
        List.add(new Pair("GROWTHMULCH", "Growth Mulch"));
        List.add(new Pair("DAMPMULCH", "Damp Mulch"));
        List.add(new Pair("STABLEMULCH", "Stable Mulch"));
        List.add(new Pair("GOOEYMULCH", "Gooey Mulch"));
        List.add(new Pair("SHOALSALT", "Shoal Salt"));
        List.add(new Pair("SHOALSHELL", "Shoal Shell"));
        List.add(new Pair("ODDKEYSTONE", "Odd Keystone"));
        List.add(new Pair("REDNECTAR", "Red Nectar"));
        List.add(new Pair("YELLOWNECTAR", "Yellow Nectar"));
        List.add(new Pair("PINKNECTAR", "Pink Nectar"));
        List.add(new Pair("PURPLENECTAR", "Purple Nectar"));
        List.add(new Pair("AIRBALLOON", "Air Balloon"));
        List.add(new Pair("BRIGHTPOWDER", "Bright Powder"));
        List.add(new Pair("EVIOLITE", "Eviolite"));
        List.add(new Pair("FLOATSTONE", "Float Stone"));
        List.add(new Pair("DESTINYKNOT", "Destiny Knot"));
        List.add(new Pair("ROCKYHELMET", "Rocky Helmet"));
        List.add(new Pair("ASSAULTVEST", "Assault Vest"));
        List.add(new Pair("SAFETYGOGGLES", "Safety Goggles"));
        List.add(new Pair("PROTECTIVEPADS", "Protective Pads"));
        List.add(new Pair("HEAVYDUTYBOOTS", "Heavy-Duty Boots"));
        List.add(new Pair("UTILITYUMBRELLA", "Utility Umbrella"));
        List.add(new Pair("EJECTBUTTON", "Eject Button"));
        List.add(new Pair("EJECTPACK", "Eject Pack"));
        List.add(new Pair("REDCARD", "Red Card"));
        List.add(new Pair("SHEDSHELL", "Shed Shell"));
        List.add(new Pair("SMOKEBALL", "Smoke Ball"));
        List.add(new Pair("LUCKYEGG", "Lucky Egg"));
        List.add(new Pair("EXPSHARE", "Exp. Share"));
        List.add(new Pair("AMULETCOIN", "Amulet Coin"));
        List.add(new Pair("SOOTHEBELL", "Soothe Bell"));
        List.add(new Pair("CLEANSETAG", "Cleanse Tag"));
        List.add(new Pair("CHOICEBAND", "Choice Band"));
        List.add(new Pair("CHOICESPECS", "Choice Specs"));
        List.add(new Pair("CHOICESCARF", "Choice Scarf"));
        List.add(new Pair("HEATROCK", "Heat Rock"));
        List.add(new Pair("DAMPROCK", "Damp Rock"));
        List.add(new Pair("SMOOTHROCK", "Smooth Rock"));
        List.add(new Pair("ICYROCK", "Icy Rock"));
        List.add(new Pair("TERRAINEXTENDER", "Terrain Extender"));
        List.add(new Pair("LIGHTCLAY", "Light Clay"));
        List.add(new Pair("GRIPCLAW", "Grip Claw"));
        List.add(new Pair("BINDINGBAND", "Binding Band"));
        List.add(new Pair("BIGROOT", "Big Root"));
        List.add(new Pair("BLACKSLUDGE", "Black Sludge"));
        List.add(new Pair("LEFTOVERS", "Leftovers"));
        List.add(new Pair("SHELLBELL", "Shell Bell"));
        List.add(new Pair("MENTALHERB", "Mental Herb"));
        List.add(new Pair("WHITEHERB", "White Herb"));
        List.add(new Pair("POWERHERB", "Power Herb"));
        List.add(new Pair("ABSORBBULB", "Absorb Bulb"));
        List.add(new Pair("CELLBATTERY", "Cell Battery"));
        List.add(new Pair("LUMINOUSMOSS", "Luminous Moss"));
        List.add(new Pair("SNOWBALL", "Snowball"));
        List.add(new Pair("WEAKNESSPOLICY", "Weakness Policy"));
        List.add(new Pair("BLUNDERPOLICY", "Blunder Policy"));
        List.add(new Pair("THROATSPRAY", "Throat Spray"));
        List.add(new Pair("ADRENALINEORB", "Adrenaline Orb"));
        List.add(new Pair("ROOMSERVICE", "Room Service"));
        List.add(new Pair("ELECTRICSEED", "Electric Seed"));
        List.add(new Pair("GRASSYSEED", "Grassy Seed"));
        List.add(new Pair("MISTYSEED", "Misty Seed"));
        List.add(new Pair("PSYCHICSEED", "Psychic Seed"));
        List.add(new Pair("LIFEORB", "Life Orb"));
        List.add(new Pair("EXPERTBELT", "Expert Belt"));
        List.add(new Pair("METRONOME", "Metronome"));
        List.add(new Pair("MUSCLEBAND", "Muscle Band"));
        List.add(new Pair("WISEGLASSES", "Wise Glasses"));
        List.add(new Pair("RAZORCLAW", "Razor Claw"));
        List.add(new Pair("SCOPELENS", "Scope Lens"));
        List.add(new Pair("WIDELENS", "Wide Lens"));
        List.add(new Pair("ZOOMLENS", "Zoom Lens"));
        List.add(new Pair("KINGSROCK", "King's Rock"));
        List.add(new Pair("RAZORFANG", "Razor Fang"));
        List.add(new Pair("LAGGINGTAIL", "Lagging Tail"));
        List.add(new Pair("QUICKCLAW", "Quick Claw"));
        List.add(new Pair("FOCUSBAND", "Focus Band"));
        List.add(new Pair("FOCUSSASH", "Focus Sash"));
        List.add(new Pair("FLAMEORB", "Flame Orb"));
        List.add(new Pair("TOXICORB", "Toxic Orb"));
        List.add(new Pair("STICKYBARB", "Sticky Barb"));
        List.add(new Pair("IRONBALL", "Iron Ball"));
        List.add(new Pair("RINGTARGET", "Ring Target"));
        List.add(new Pair("MACHOBRACE", "Macho Brace"));
        List.add(new Pair("POWERWEIGHT", "Power Weight"));
        List.add(new Pair("POWERBRACER", "Power Bracer"));
        List.add(new Pair("POWERBELT", "Power Belt"));
        List.add(new Pair("POWERLENS", "Power Lens"));
        List.add(new Pair("POWERBAND", "Power Band"));
        List.add(new Pair("POWERANKLET", "Power Anklet"));
        List.add(new Pair("LAXINCENSE", "Lax Incense"));
        List.add(new Pair("FULLINCENSE", "Full Incense"));
        List.add(new Pair("LUCKINCENSE", "Luck Incense"));
        List.add(new Pair("PUREINCENSE", "Pure Incense"));
        List.add(new Pair("SEAINCENSE", "Sea Incense"));
        List.add(new Pair("WAVEINCENSE", "Wave Incense"));
        List.add(new Pair("ROSEINCENSE", "Rose Incense"));
        List.add(new Pair("ODDINCENSE", "Odd Incense"));
        List.add(new Pair("ROCKINCENSE", "Rock Incense"));
        List.add(new Pair("CHARCOAL", "Charcoal"));
        List.add(new Pair("MYSTICWATER", "Mystic Water"));
        List.add(new Pair("MAGNET", "Magnet"));
        List.add(new Pair("MIRACLESEED", "Miracle Seed"));
        List.add(new Pair("NEVERMELTICE", "Never-Melt Ice"));
        List.add(new Pair("BLACKBELT", "Black Belt"));
        List.add(new Pair("POISONBARB", "Poison Barb"));
        List.add(new Pair("SOFTSAND", "Soft Sand"));
        List.add(new Pair("SHARPBEAK", "Sharp Beak"));
        List.add(new Pair("TWISTEDSPOON", "Twisted Spoon"));
        List.add(new Pair("SILVERPOWDER", "Silver Powder"));
        List.add(new Pair("HARDSTONE", "Hard Stone"));
        List.add(new Pair("SPELLTAG", "Spell Tag"));
        List.add(new Pair("DRAGONFANG", "Dragon Fang"));
        List.add(new Pair("BLACKGLASSES", "Black Glasses"));
        List.add(new Pair("METALCOAT", "Metal Coat"));
        List.add(new Pair("SILKSCARF", "Silk Scarf"));
        List.add(new Pair("FLAMEPLATE", "Flame Plate"));
        List.add(new Pair("SPLASHPLATE", "Splash Plate"));
        List.add(new Pair("ZAPPLATE", "Zap Plate"));
        List.add(new Pair("MEADOWPLATE", "Meadow Plate"));
        List.add(new Pair("ICICLEPLATE", "Icicle Plate"));
        List.add(new Pair("FISTPLATE", "Fist Plate"));
        List.add(new Pair("TOXICPLATE", "Toxic Plate"));
        List.add(new Pair("EARTHPLATE", "Earth Plate"));
        List.add(new Pair("SKYPLATE", "Sky Plate"));
        List.add(new Pair("MINDPLATE", "Mind Plate"));
        List.add(new Pair("INSECTPLATE", "Insect Plate"));
        List.add(new Pair("STONEPLATE", "Stone Plate"));
        List.add(new Pair("SPOOKYPLATE", "Spooky Plate"));
        List.add(new Pair("DRACOPLATE", "Draco Plate"));
        List.add(new Pair("DREADPLATE", "Dread Plate"));
        List.add(new Pair("IRONPLATE", "Iron Plate"));
        List.add(new Pair("PIXIEPLATE", "Pixie Plate"));
        List.add(new Pair("FIREGEM", "Fire Gem"));
        List.add(new Pair("WATERGEM", "Water Gem"));
        List.add(new Pair("ELECTRICGEM", "Electric Gem"));
        List.add(new Pair("GRASSGEM", "Grass Gem"));
        List.add(new Pair("ICEGEM", "Ice Gem"));
        List.add(new Pair("FIGHTINGGEM", "Fighting Gem"));
        List.add(new Pair("POISONGEM", "Poison Gem"));
        List.add(new Pair("GROUNDGEM", "Ground Gem"));
        List.add(new Pair("FLYINGGEM", "Flying Gem"));
        List.add(new Pair("PSYCHICGEM", "Psychic Gem"));
        List.add(new Pair("BUGGEM", "Bug Gem"));
        List.add(new Pair("ROCKGEM", "Rock Gem"));
        List.add(new Pair("GHOSTGEM", "Ghost Gem"));
        List.add(new Pair("DRAGONGEM", "Dragon Gem"));
        List.add(new Pair("DARKGEM", "Dark Gem"));
        List.add(new Pair("STEELGEM", "Steel Gem"));
        List.add(new Pair("FAIRYGEM", "Fairy Gem"));
        List.add(new Pair("NORMALGEM", "Normal Gem"));
        List.add(new Pair("LIGHTBALL", "Light Ball"));
        List.add(new Pair("LUCKYPUNCH", "Lucky Punch"));
        List.add(new Pair("METALPOWDER", "Metal Powder"));
        List.add(new Pair("QUICKPOWDER", "Quick Powder"));
        List.add(new Pair("THICKCLUB", "Thick Club"));
        List.add(new Pair("LEEK", "Leek"));
        List.add(new Pair("SOULDEW", "Soul Dew"));
        List.add(new Pair("DEEPSEATOOTH", "Deep Sea Tooth"));
        List.add(new Pair("DEEPSEASCALE", "Deep Sea Scale"));
        List.add(new Pair("ADAMANTORB", "Adamant Orb"));
        List.add(new Pair("LUSTROUSORB", "Lustrous Orb"));
        List.add(new Pair("GRISEOUSORB", "Griseous Orb"));
        List.add(new Pair("RUSTEDSWORD", "Rusted Sword"));
        List.add(new Pair("RUSTEDSHIELD", "Rusted Shield"));
        List.add(new Pair("DOUSEDRIVE", "Douse Drive"));
        List.add(new Pair("SHOCKDRIVE", "Shock Drive"));
        List.add(new Pair("BURNDRIVE", "Burn Drive"));
        List.add(new Pair("CHILLDRIVE", "Chill Drive"));
        List.add(new Pair("FIREMEMORY", "Fire Memory"));
        List.add(new Pair("WATERMEMORY", "Water Memory"));
        List.add(new Pair("ELECTRICMEMORY", "Electric Memory"));
        List.add(new Pair("GRASSMEMORY", "Grass Memory"));
        List.add(new Pair("ICEMEMORY", "Ice Memory"));
        List.add(new Pair("FIGHTINGMEMORY", "Fighting Memory"));
        List.add(new Pair("POISONMEMORY", "Poison Memory"));
        List.add(new Pair("GROUNDMEMORY", "Ground Memory"));
        List.add(new Pair("FLYINGMEMORY", "Flying Memory"));
        List.add(new Pair("PSYCHICMEMORY", "Psychic Memory"));
        List.add(new Pair("BUGMEMORY", "Bug Memory"));
        List.add(new Pair("ROCKMEMORY", "Rock Memory"));
        List.add(new Pair("GHOSTMEMORY", "Ghost Memory"));
        List.add(new Pair("DRAGONMEMORY", "Dragon Memory"));
        List.add(new Pair("DARKMEMORY", "Dark Memory"));
        List.add(new Pair("STEELMEMORY", "Steel Memory"));
        List.add(new Pair("FAIRYMEMORY", "Fairy Memory"));
        List.add(new Pair("EVERSTONE", "Everstone"));
        List.add(new Pair("DRAGONSCALE", "Dragon Scale"));
        List.add(new Pair("UPGRADE", "Upgrade"));
        List.add(new Pair("DUBIOUSDISC", "Dubious Disc"));
        List.add(new Pair("PROTECTOR", "Protector"));
        List.add(new Pair("ELECTIRIZER", "Electirizer"));
        List.add(new Pair("MAGMARIZER", "Magmarizer"));
        List.add(new Pair("REAPERCLOTH", "Reaper Cloth"));
        List.add(new Pair("PRISMSCALE", "Prism Scale"));
        List.add(new Pair("OVALSTONE", "Oval Stone"));
        List.add(new Pair("WHIPPEDDREAM", "Whipped Dream"));
        List.add(new Pair("SACHET", "Sachet"));
        List.add(new Pair("STRAWBERRYSWEET", "Strawberry Sweet"));
        List.add(new Pair("LOVESWEET", "Love Sweet"));
        List.add(new Pair("BERRYSWEET", "Berry Sweet"));
        List.add(new Pair("CLOVERSWEET", "Clover Sweet"));
        List.add(new Pair("FLOWERSWEET", "Flower Sweet"));
        List.add(new Pair("STARSWEET", "Star Sweet"));
        List.add(new Pair("RIBBONSWEET", "Ribbon Sweet"));
        List.add(new Pair("VENUSAURITE", "Venusaurite"));
        List.add(new Pair("CHARIZARDITEX", "Charizardite X"));
        List.add(new Pair("CHARIZARDITEY", "Charizardite Y"));
        List.add(new Pair("BLASTOISINITE", "Blastoisinite"));
        List.add(new Pair("BEEDRILLITE", "Beedrillite"));
        List.add(new Pair("PIDGEOTITE", "Pidgeotite"));
        List.add(new Pair("ALAKAZITE", "Alakazite"));
        List.add(new Pair("SLOWBRONITE", "Slowbronite"));
        List.add(new Pair("GENGARITE", "Gengarite"));
        List.add(new Pair("KANGASKHANITE", "Kangaskhanite"));
        List.add(new Pair("PINSIRITE", "Pinsirite"));
        List.add(new Pair("GYARADOSITE", "Gyaradosite"));
        List.add(new Pair("AERODACTYLITE", "Aerodactylite"));
        List.add(new Pair("MEWTWONITEX", "Mewtwonite X"));
        List.add(new Pair("MEWTWONITEY", "Mewtwonite Y"));
        List.add(new Pair("AMPHAROSITE", "Ampharosite"));
        List.add(new Pair("STEELIXITE", "Steelixite"));
        List.add(new Pair("SCIZORITE", "Scizorite"));
        List.add(new Pair("HERACRONITE", "Heracronite"));
        List.add(new Pair("HOUNDOOMINITE", "Houndoominite"));
        List.add(new Pair("TYRANITARITE", "Tyranitarite"));
        List.add(new Pair("SCEPTILITE", "Sceptilite"));
        List.add(new Pair("BLAZIKENITE", "Blazikenite"));
        List.add(new Pair("SWAMPERTITE", "Swampertite"));
        List.add(new Pair("GARDEVOIRITE", "Gardevoirite"));
        List.add(new Pair("SABLENITE", "Sablenite"));
        List.add(new Pair("MAWILITE", "Mawilite"));
        List.add(new Pair("AGGRONITE", "Aggronite"));
        List.add(new Pair("MEDICHAMITE", "Medichamite"));
        List.add(new Pair("MANECTITE", "Manectite"));
        List.add(new Pair("SHARPEDONITE", "Sharpedonite"));
        List.add(new Pair("CAMERUPTITE", "Cameruptite"));
        List.add(new Pair("ALTARIANITE", "Altarianite"));
        List.add(new Pair("BANETTITE", "Banettite"));
        List.add(new Pair("ABSOLITE", "Absolite"));
        List.add(new Pair("GLALITITE", "Glalitite"));
        List.add(new Pair("SALAMENCITE", "Salamencite"));
        List.add(new Pair("METAGROSSITE", "Metagrossite"));
        List.add(new Pair("LATIASITE", "Latiasite"));
        List.add(new Pair("LATIOSITE", "Latiosite"));
        List.add(new Pair("LOPUNNITE", "Lopunnite"));
        List.add(new Pair("GARCHOMPITE", "Garchompite"));
        List.add(new Pair("LUCARIONITE", "Lucarionite"));
        List.add(new Pair("ABOMASITE", "Abomasite"));
        List.add(new Pair("GALLADITE", "Galladite"));
        List.add(new Pair("AUDINITE", "Audinite"));
        List.add(new Pair("DIANCITE", "Diancite"));
        List.add(new Pair("REDORB", "Red Orb"));
        List.add(new Pair("BLUEORB", "Blue Orb"));
        List.add(new Pair("POTION", "Potion"));
        List.add(new Pair("SUPERPOTION", "Super Potion"));
        List.add(new Pair("HYPERPOTION", "Hyper Potion"));
        List.add(new Pair("MAXPOTION", "Max Potion"));
        List.add(new Pair("FULLRESTORE", "Full Restore"));
        List.add(new Pair("SACREDASH", "Sacred Ash"));
        List.add(new Pair("AWAKENING", "Awakening"));
        List.add(new Pair("ANTIDOTE", "Antidote"));
        List.add(new Pair("BURNHEAL", "Burn Heal"));
        List.add(new Pair("PARALYZEHEAL", "Paralyze Heal"));
        List.add(new Pair("ICEHEAL", "Ice Heal"));
        List.add(new Pair("FULLHEAL", "Full Heal"));
        List.add(new Pair("PEWTERCRUNCHIES", "Pewter Crunchies"));
        List.add(new Pair("RAGECANDYBAR", "Rage Candy Bar"));
        List.add(new Pair("LAVACOOKIE", "Lava Cookie"));
        List.add(new Pair("OLDGATEAU", "Old Gateau"));
        List.add(new Pair("CASTELIACONE", "Casteliacone"));
        List.add(new Pair("LUMIOSEGALETTE", "Lumiose Galette"));
        List.add(new Pair("SHALOURSABLE", "Shalour Sable"));
        List.add(new Pair("BIGMALASADA", "Big Malasada"));
        List.add(new Pair("REVIVE", "Revive"));
        List.add(new Pair("MAXREVIVE", "Max Revive"));
        List.add(new Pair("BERRYJUICE", "Berry Juice"));
        List.add(new Pair("SWEETHEART", "Sweet Heart"));
        List.add(new Pair("FRESHWATER", "Fresh Water"));
        List.add(new Pair("SODAPOP", "Soda Pop"));
        List.add(new Pair("LEMONADE", "Lemonade"));
        List.add(new Pair("MOOMOOMILK", "Moomoo Milk"));
        List.add(new Pair("ENERGYPOWDER", "Energy Powder"));
        List.add(new Pair("ENERGYROOT", "Energy Root"));
        List.add(new Pair("HEALPOWDER", "Heal Powder"));
        List.add(new Pair("REVIVALHERB", "Revival Herb"));
        List.add(new Pair("MAXHONEY", "Max Honey"));
        List.add(new Pair("ETHER", "Ether"));
        List.add(new Pair("MAXETHER", "Max Ether"));
        List.add(new Pair("ELIXIR", "Elixir"));
        List.add(new Pair("MAXELIXIR", "Max Elixir"));
        List.add(new Pair("PPUP", "PP Up"));
        List.add(new Pair("PPMAX", "PP Max"));
        List.add(new Pair("HPUP", "HP Up"));
        List.add(new Pair("PROTEIN", "Protein"));
        List.add(new Pair("IRON", "Iron"));
        List.add(new Pair("CALCIUM", "Calcium"));
        List.add(new Pair("ZINC", "Zinc"));
        List.add(new Pair("CARBOS", "Carbos"));
        List.add(new Pair("HEALTHFEATHER", "Health Feather"));
        List.add(new Pair("MUSCLEFEATHER", "Muscle Feather"));
        List.add(new Pair("RESISTFEATHER", "Resist Feather"));
        List.add(new Pair("GENIUSFEATHER", "Genius Feather"));
        List.add(new Pair("CLEVERFEATHER", "Clever Feather"));
        List.add(new Pair("SWIFTFEATHER", "Swift Feather"));
        List.add(new Pair("LONELYMINT", "Lonely Mint"));
        List.add(new Pair("ADAMANTMINT", "Adamant Mint"));
        List.add(new Pair("NAUGHTYMINT", "Naughty Mint"));
        List.add(new Pair("BRAVEMINT", "Brave Mint"));
        List.add(new Pair("BOLDMINT", "Bold Mint"));
        List.add(new Pair("IMPISHMINT", "Impish Mint"));
        List.add(new Pair("LAXMINT", "Lax Mint"));
        List.add(new Pair("RELAXEDMINT", "Relaxed Mint"));
        List.add(new Pair("MODESTMINT", "Modest Mint"));
        List.add(new Pair("MILDMINT", "Mild Mint"));
        List.add(new Pair("RASHMINT", "Rash Mint"));
        List.add(new Pair("QUIETMINT", "Quiet Mint"));
        List.add(new Pair("CALMMINT", "Calm Mint"));
        List.add(new Pair("GENTLEMINT", "Gentle Mint"));
        List.add(new Pair("CAREFULMINT", "Careful Mint"));
        List.add(new Pair("SASSYMINT", "Sassy Mint"));
        List.add(new Pair("TIMIDMINT", "Timid Mint"));
        List.add(new Pair("HASTYMINT", "Hasty Mint"));
        List.add(new Pair("JOLLYMINT", "Jolly Mint"));
        List.add(new Pair("NAIVEMINT", "Naive Mint"));
        List.add(new Pair("SERIOUSMINT", "Serious Mint"));
        List.add(new Pair("ABILITYCAPSULE", "Ability Capsule"));
        List.add(new Pair("ABILITYPATCH", "Ability Patch"));
        List.add(new Pair("EXPCANDYXS", "Exp. Candy XS"));
        List.add(new Pair("EXPCANDYS", "Exp. Candy S"));
        List.add(new Pair("EXPCANDYM", "Exp. Candy M"));
        List.add(new Pair("EXPCANDYL", "Exp. Candy L"));
        List.add(new Pair("EXPCANDYXL", "Exp. Candy XL"));
        List.add(new Pair("RARECANDY", "Rare Candy"));
        List.add(new Pair("MASTERBALL", "Master Ball"));
        List.add(new Pair("ULTRABALL", "Ultra Ball"));
        List.add(new Pair("GREATBALL", "Great Ball"));
        List.add(new Pair("POKEBALL", "Poké Ball"));
        List.add(new Pair("SAFARIBALL", "Safari Ball"));
        List.add(new Pair("SPORTBALL", "Sport Ball"));
        List.add(new Pair("NETBALL", "Net Ball"));
        List.add(new Pair("DIVEBALL", "Dive Ball"));
        List.add(new Pair("NESTBALL", "Nest Ball"));
        List.add(new Pair("REPEATBALL", "Repeat Ball"));
        List.add(new Pair("TIMERBALL", "Timer Ball"));
        List.add(new Pair("LUXURYBALL", "Luxury Ball"));
        List.add(new Pair("PREMIERBALL", "Premier Ball"));
        List.add(new Pair("DUSKBALL", "Dusk Ball"));
        List.add(new Pair("HEALBALL", "Heal Ball"));
        List.add(new Pair("QUICKBALL", "Quick Ball"));
        List.add(new Pair("CHERISHBALL", "Cherish Ball"));
        List.add(new Pair("FASTBALL", "Fast Ball"));
        List.add(new Pair("LEVELBALL", "Level Ball"));
        List.add(new Pair("LUREBALL", "Lure Ball"));
        List.add(new Pair("HEAVYBALL", "Heavy Ball"));
        List.add(new Pair("LOVEBALL", "Love Ball"));
        List.add(new Pair("FRIENDBALL", "Friend Ball"));
        List.add(new Pair("MOONBALL", "Moon Ball"));
        List.add(new Pair("DREAMBALL", "Dream Ball"));
        List.add(new Pair("BEASTBALL", "Beast Ball"));
        List.add(new Pair("TM01", "TM01"));
        List.add(new Pair("TM02", "TM02"));
        List.add(new Pair("TM03", "TM03"));
        List.add(new Pair("TM04", "TM04"));
        List.add(new Pair("TM05", "TM05"));
        List.add(new Pair("TM06", "TM06"));
        List.add(new Pair("TM07", "TM07"));
        List.add(new Pair("TM08", "TM08"));
        List.add(new Pair("TM09", "TM09"));
        List.add(new Pair("TM10", "TM10"));
        List.add(new Pair("TM11", "TM11"));
        List.add(new Pair("TM12", "TM12"));
        List.add(new Pair("TM13", "TM13"));
        List.add(new Pair("TM14", "TM14"));
        List.add(new Pair("TM15", "TM15"));
        List.add(new Pair("TM16", "TM16"));
        List.add(new Pair("TM17", "TM17"));
        List.add(new Pair("TM18", "TM18"));
        List.add(new Pair("TM19", "TM19"));
        List.add(new Pair("TM20", "TM20"));
        List.add(new Pair("TM21", "TM21"));
        List.add(new Pair("TM22", "TM22"));
        List.add(new Pair("TM23", "TM23"));
        List.add(new Pair("TM24", "TM24"));
        List.add(new Pair("TM25", "TM25"));
        List.add(new Pair("TM26", "TM26"));
        List.add(new Pair("TM27", "TM27"));
        List.add(new Pair("TM28", "TM28"));
        List.add(new Pair("TM29", "TM29"));
        List.add(new Pair("TM30", "TM30"));
        List.add(new Pair("TM31", "TM31"));
        List.add(new Pair("TM32", "TM32"));
        List.add(new Pair("TM33", "TM33"));
        List.add(new Pair("TM34", "TM34"));
        List.add(new Pair("TM35", "TM35"));
        List.add(new Pair("TM36", "TM36"));
        List.add(new Pair("TM37", "TM37"));
        List.add(new Pair("TM38", "TM38"));
        List.add(new Pair("TM39", "TM39"));
        List.add(new Pair("TM40", "TM40"));
        List.add(new Pair("TM41", "TM41"));
        List.add(new Pair("TM42", "TM42"));
        List.add(new Pair("TM43", "TM43"));
        List.add(new Pair("TM44", "TM44"));
        List.add(new Pair("TM45", "TM45"));
        List.add(new Pair("TM46", "TM46"));
        List.add(new Pair("TM47", "TM47"));
        List.add(new Pair("TM48", "TM48"));
        List.add(new Pair("TM49", "TM49"));
        List.add(new Pair("TM50", "TM50"));
        List.add(new Pair("TM51", "TM51"));
        List.add(new Pair("TM52", "TM52"));
        List.add(new Pair("TM53", "TM53"));
        List.add(new Pair("TM54", "TM54"));
        List.add(new Pair("TM55", "TM55"));
        List.add(new Pair("TM56", "TM56"));
        List.add(new Pair("TM57", "TM57"));
        List.add(new Pair("TM58", "TM58"));
        List.add(new Pair("TM59", "TM59"));
        List.add(new Pair("TM60", "TM60"));
        List.add(new Pair("TM61", "TM61"));
        List.add(new Pair("TM62", "TM62"));
        List.add(new Pair("TM63", "TM63"));
        List.add(new Pair("TM64", "TM64"));
        List.add(new Pair("TM65", "TM65"));
        List.add(new Pair("TM66", "TM66"));
        List.add(new Pair("TM67", "TM67"));
        List.add(new Pair("TM68", "TM68"));
        List.add(new Pair("TM69", "TM69"));
        List.add(new Pair("TM70", "TM70"));
        List.add(new Pair("TM71", "TM71"));
        List.add(new Pair("TM72", "TM72"));
        List.add(new Pair("TM73", "TM73"));
        List.add(new Pair("TM74", "TM74"));
        List.add(new Pair("TM75", "TM75"));
        List.add(new Pair("TM76", "TM76"));
        List.add(new Pair("TM77", "TM77"));
        List.add(new Pair("TM78", "TM78"));
        List.add(new Pair("TM79", "TM79"));
        List.add(new Pair("TM80", "TM80"));
        List.add(new Pair("TM81", "TM81"));
        List.add(new Pair("TM82", "TM82"));
        List.add(new Pair("TM83", "TM83"));
        List.add(new Pair("TM84", "TM84"));
        List.add(new Pair("TM85", "TM85"));
        List.add(new Pair("TM86", "TM86"));
        List.add(new Pair("TM87", "TM87"));
        List.add(new Pair("TM88", "TM88"));
        List.add(new Pair("TM89", "TM89"));
        List.add(new Pair("TM90", "TM90"));
        List.add(new Pair("TM91", "TM91"));
        List.add(new Pair("TM92", "TM92"));
        List.add(new Pair("TM93", "TM93"));
        List.add(new Pair("TM94", "TM94"));
        List.add(new Pair("TM95", "TM95"));
        List.add(new Pair("TM96", "TM96"));
        List.add(new Pair("TM97", "TM97"));
        List.add(new Pair("TM98", "TM98"));
        List.add(new Pair("TM99", "TM99"));
        List.add(new Pair("TM100", "TM100"));
        List.add(new Pair("HM01", "HM01"));
        List.add(new Pair("HM02", "HM02"));
        List.add(new Pair("HM03", "HM03"));
        List.add(new Pair("HM04", "HM04"));
        List.add(new Pair("HM05", "HM05"));
        List.add(new Pair("HM06", "HM06"));
        List.add(new Pair("CHERIBERRY", "Cheri Berry"));
        List.add(new Pair("CHESTOBERRY", "Chesto Berry"));
        List.add(new Pair("PECHABERRY", "Pecha Berry"));
        List.add(new Pair("RAWSTBERRY", "Rawst Berry"));
        List.add(new Pair("ASPEARBERRY", "Aspear Berry"));
        List.add(new Pair("LEPPABERRY", "Leppa Berry"));
        List.add(new Pair("ORANBERRY", "Oran Berry"));
        List.add(new Pair("PERSIMBERRY", "Persim Berry"));
        List.add(new Pair("LUMBERRY", "Lum Berry"));
        List.add(new Pair("SITRUSBERRY", "Sitrus Berry"));
        List.add(new Pair("FIGYBERRY", "Figy Berry"));
        List.add(new Pair("WIKIBERRY", "Wiki Berry"));
        List.add(new Pair("MAGOBERRY", "Mago Berry"));
        List.add(new Pair("AGUAVBERRY", "Aguav Berry"));
        List.add(new Pair("IAPAPABERRY", "Iapapa Berry"));
        List.add(new Pair("RAZZBERRY", "Razz Berry"));
        List.add(new Pair("BLUKBERRY", "Bluk Berry"));
        List.add(new Pair("NANABBERRY", "Nanab Berry"));
        List.add(new Pair("WEPEARBERRY", "Wepear Berry"));
        List.add(new Pair("PINAPBERRY", "Pinap Berry"));
        List.add(new Pair("POMEGBERRY", "Pomeg Berry"));
        List.add(new Pair("KELPSYBERRY", "Kelpsy Berry"));
        List.add(new Pair("QUALOTBERRY", "Qualot Berry"));
        List.add(new Pair("HONDEWBERRY", "Hondew Berry"));
        List.add(new Pair("GREPABERRY", "Grepa Berry"));
        List.add(new Pair("TAMATOBERRY", "Tamato Berry"));
        List.add(new Pair("CORNNBERRY", "Cornn Berry"));
        List.add(new Pair("MAGOSTBERRY", "Magost Berry"));
        List.add(new Pair("RABUTABERRY", "Rabuta Berry"));
        List.add(new Pair("NOMELBERRY", "Nomel Berry"));
        List.add(new Pair("SPELONBERRY", "Spelon Berry"));
        List.add(new Pair("PAMTREBERRY", "Pamtre Berry"));
        List.add(new Pair("WATMELBERRY", "Watmel Berry"));
        List.add(new Pair("DURINBERRY", "Durin Berry"));
        List.add(new Pair("BELUEBERRY", "Belue Berry"));
        List.add(new Pair("OCCABERRY", "Occa Berry"));
        List.add(new Pair("PASSHOBERRY", "Passho Berry"));
        List.add(new Pair("WACANBERRY", "Wacan Berry"));
        List.add(new Pair("RINDOBERRY", "Rindo Berry"));
        List.add(new Pair("YACHEBERRY", "Yache Berry"));
        List.add(new Pair("CHOPLEBERRY", "Chople Berry"));
        List.add(new Pair("KEBIABERRY", "Kebia Berry"));
        List.add(new Pair("SHUCABERRY", "Shuca Berry"));
        List.add(new Pair("COBABERRY", "Coba Berry"));
        List.add(new Pair("PAYAPABERRY", "Payapa Berry"));
        List.add(new Pair("TANGABERRY", "Tanga Berry"));
        List.add(new Pair("CHARTIBERRY", "Charti Berry"));
        List.add(new Pair("KASIBBERRY", "Kasib Berry"));
        List.add(new Pair("HABANBERRY", "Haban Berry"));
        List.add(new Pair("COLBURBERRY", "Colbur Berry"));
        List.add(new Pair("BABIRIBERRY", "Babiri Berry"));
        List.add(new Pair("ROSELIBERRY", "Roseli Berry"));
        List.add(new Pair("CHILANBERRY", "Chilan Berry"));
        List.add(new Pair("LIECHIBERRY", "Liechi Berry"));
        List.add(new Pair("GANLONBERRY", "Ganlon Berry"));
        List.add(new Pair("SALACBERRY", "Salac Berry"));
        List.add(new Pair("PETAYABERRY", "Petaya Berry"));
        List.add(new Pair("APICOTBERRY", "Apicot Berry"));
        List.add(new Pair("LANSATBERRY", "Lansat Berry"));
        List.add(new Pair("STARFBERRY", "Starf Berry"));
        List.add(new Pair("ENIGMABERRY", "Enigma Berry"));
        List.add(new Pair("MICLEBERRY", "Micle Berry"));
        List.add(new Pair("CUSTAPBERRY", "Custap Berry"));
        List.add(new Pair("JABOCABERRY", "Jaboca Berry"));
        List.add(new Pair("ROWAPBERRY", "Rowap Berry"));
        List.add(new Pair("KEEBERRY", "Kee Berry"));
        List.add(new Pair("MARANGABERRY", "Maranga Berry"));
        List.add(new Pair("GRASSMAIL", "Grass Mail"));
        List.add(new Pair("FLAMEMAIL", "Flame Mail"));
        List.add(new Pair("BUBBLEMAIL", "Bubble Mail"));
        List.add(new Pair("BLOOMMAIL", "Bloom Mail"));
        List.add(new Pair("TUNNELMAIL", "Tunnel Mail"));
        List.add(new Pair("STEELMAIL", "Steel Mail"));
        List.add(new Pair("HEARTMAIL", "Heart Mail"));
        List.add(new Pair("SNOWMAIL", "Snow Mail"));
        List.add(new Pair("SPACEMAIL", "Space Mail"));
        List.add(new Pair("AIRMAIL", "Air Mail"));
        List.add(new Pair("MOSAICMAIL", "Mosaic Mail"));
        List.add(new Pair("BRICKMAIL", "Brick Mail"));
        List.add(new Pair("XATTACK", "X Attack"));
        List.add(new Pair("XATTACK2", "X Attack 2"));
        List.add(new Pair("XATTACK3", "X Attack 3"));
        List.add(new Pair("XATTACK6", "X Attack 6"));
        List.add(new Pair("XDEFENSE", "X Defense"));
        List.add(new Pair("XDEFENSE2", "X Defense 2"));
        List.add(new Pair("XDEFENSE3", "X Defense 3"));
        List.add(new Pair("XDEFENSE6", "X Defense 6"));
        List.add(new Pair("XSPATK", "X Sp. Atk"));
        List.add(new Pair("XSPATK2", "X Sp. Atk 2"));
        List.add(new Pair("XSPATK3", "X Sp. Atk 3"));
        List.add(new Pair("XSPATK6", "X Sp. Atk 6"));
        List.add(new Pair("XSPDEF", "X Sp. Def"));
        List.add(new Pair("XSPDEF2", "X Sp. Def 2"));
        List.add(new Pair("XSPDEF3", "X Sp. Def 3"));
        List.add(new Pair("XSPDEF6", "X Sp. Def 6"));
        List.add(new Pair("XSPEED", "X Speed"));
        List.add(new Pair("XSPEED2", "X Speed 2"));
        List.add(new Pair("XSPEED3", "X Speed 3"));
        List.add(new Pair("XSPEED6", "X Speed 6"));
        List.add(new Pair("XACCURACY", "X Accuracy"));
        List.add(new Pair("XACCURACY2", "X Accuracy 2"));
        List.add(new Pair("XACCURACY3", "X Accuracy 3"));
        List.add(new Pair("XACCURACY6", "X Accuracy 6"));
        List.add(new Pair("MAXMUSHROOMS", "Max Mushrooms"));
        List.add(new Pair("DIREHIT", "Dire Hit"));
        List.add(new Pair("DIREHIT2", "Dire Hit 2"));
        List.add(new Pair("DIREHIT3", "Dire Hit 3"));
        List.add(new Pair("GUARDSPEC", "Guard Spec."));
        List.add(new Pair("RESETURGE", "Reset Urge"));
        List.add(new Pair("ABILITYURGE", "Ability Urge"));
        List.add(new Pair("ITEMURGE", "Item Urge"));
        List.add(new Pair("ITEMDROP", "Item Drop"));
        List.add(new Pair("BLUEFLUTE", "Blue Flute"));
        List.add(new Pair("YELLOWFLUTE", "Yellow Flute"));
        List.add(new Pair("REDFLUTE", "Red Flute"));
        List.add(new Pair("POKEDOLL", "Poké Doll"));
        List.add(new Pair("FLUFFYTAIL", "Fluffy Tail"));
        List.add(new Pair("POKETOY", "Poké Toy"));
        List.add(new Pair("BICYCLE", "Bicycle"));
        List.add(new Pair("OLDROD", "Old Rod"));
        List.add(new Pair("GOODROD", "Good Rod"));
        List.add(new Pair("SUPERROD", "Super Rod"));
        List.add(new Pair("ITEMFINDER", "Itemfinder"));
        List.add(new Pair("DOWSINGMACHINE", "Dowsing Machine"));
        List.add(new Pair("POKERADAR", "Poké Radar"));
        List.add(new Pair("TOWNMAP", "Town Map"));
        List.add(new Pair("ESCAPEROPE", "Escape Rope"));
        List.add(new Pair("COINCASE", "Coin Case"));
        List.add(new Pair("POKEFLUTE", "Poké Flute"));
        List.add(new Pair("SOOTSACK", "Soot Sack"));
        List.add(new Pair("SILPHSCOPE", "Silph Scope"));
        List.add(new Pair("DEVONSCOPE", "Devon Scope"));
        List.add(new Pair("SQUIRTBOTTLE", "Squirt Bottle"));
        List.add(new Pair("SPRAYDUCK", "Sprayduck"));
        List.add(new Pair("WAILMERPAIL", "Wailmer Pail"));
        List.add(new Pair("SPRINKLOTAD", "Sprinklotad"));
        List.add(new Pair("GRACIDEA", "Gracidea"));
        List.add(new Pair("REVEALGLASS", "Reveal Glass"));
        List.add(new Pair("PRISONBOTTLE", "Prison Bottle"));
        List.add(new Pair("ROTOMCATALOG", "Rotom Catalog"));
        List.add(new Pair("ZYGARDECUBE", "Zygarde Cube"));
        List.add(new Pair("DNASPLICERS", "DNA Splicers"));
        List.add(new Pair("DNASPLICERSUSED", "DNA Splicers"));
        List.add(new Pair("NSOLARIZER", "N-Solarizer"));
        List.add(new Pair("NSOLARIZERUSED", "N-Solarizer"));
        List.add(new Pair("NLUNARIZER", "N-Lunarizer"));
        List.add(new Pair("NLUNARIZERUSED", "N-Lunarizer"));
        List.add(new Pair("REINSOFUNITY", "Reins of Unity"));
        List.add(new Pair("REINSOFUNITYUSED", "Reins of Unity"));
        List.add(new Pair("OVALCHARM", "Oval Charm"));
        List.add(new Pair("SHINYCHARM", "Shiny Charm"));
        List.add(new Pair("CATCHINGCHARM", "Catching Charm"));
        List.add(new Pair("EXPCHARM", "Exp. Charm"));
        List.add(new Pair("MEGARING", "Mega Ring"));
        List.add(new Pair("POKEMONBOXLINK", "Pokémon Box Link"));
        List.add(new Pair("AURORATICKET", "Aurora Ticket"));
        List.add(new Pair("OLDSEAMAP", "Old Sea Map"));
        
        // Dynamax
        List.add(new Pair("DYNAMAXBAND", "Dynamax Band"));
        List.add(new Pair("WISHINGSTAR", "Wishing Star"));
        List.add(new Pair("DYNAMAXCANDY", "Dynamax Candy"));
        List.add(new Pair("DYNAMAXCANDYXL", "Dynamax Candy XL"));
        List.add(new Pair("MAXSOUP", "Max Soup"));
        
        // Gen 9 Pack
        List.add(new Pair("BLACKAUGURITE", "Black Augurite"));
        List.add(new Pair("PEATBLOCK", "Peat Block"));
        List.add(new Pair("LINKINGCORD", "Linking Cord"));
        List.add(new Pair("ADAMANTCRYSTAL", "Adamant Crystal"));
        List.add(new Pair("LUSTROUSGLOBE", "Lustrous Globe"));
        List.add(new Pair("LEGENDPLATE", "Legend Plate"));
        List.add(new Pair("BLANKPLATE", "Blank Plate"));
        List.add(new Pair("HOPOBERRY", "Hopo Berry"));
        List.add(new Pair("GRISEOUSCORE", "Griseous Core"));
        List.add(new Pair("HISUIANPOKEBALL", "Poké Ball (Hisui)"));
        List.add(new Pair("HISUIANGREATBALL", "Great Ball (Hisui)"));
        List.add(new Pair("HISUIANULTRABALL", "Ultra Ball (Hisui)"));
        List.add(new Pair("FEATHERBALL", "Feather Ball"));
        List.add(new Pair("WINGBALL", "Wing Ball"));
        List.add(new Pair("JETBALL", "Jet Ball"));
        List.add(new Pair("HISUIANHEAVYBALL", "Heavy Ball (Hisui)"));
        List.add(new Pair("LEADENBALL", "Leaden Ball"));
        List.add(new Pair("GIGATONBALL", "Gigaton Ball"));
        List.add(new Pair("ORIGINBALL", "Origin Ball"));
        List.add(new Pair("STRANGEBALL", "Strange Ball"));
        List.add(new Pair("AUSPICIOUSARMOR", "Auspicious Armor"));
        List.add(new Pair("MALICIOUSARMOR", "Malicious Armor"));
        List.add(new Pair("SCROLLOFDARKNESS", "Scroll of Darkness"));
        List.add(new Pair("SCROLLOFWATERS", "Scroll of Waters"));
        List.add(new Pair("LEADERSCREST", "Leader's Crest"));
        List.add(new Pair("BOOSTERENERGY", "Booster Energy"));
        List.add(new Pair("ABILITYSHIELD", "Ability Shield"));
        List.add(new Pair("CLEARAMULET", "Clear Amulet"));
        List.add(new Pair("MIRRORHERB", "Mirror Herb"));
        List.add(new Pair("PUNCHINGGLOVE", "Punching Glove"));
        List.add(new Pair("COVERTCLOAK", "Covert Cloak"));
        List.add(new Pair("LOADEDDICE", "Loaded Dice"));
        List.add(new Pair("GIMMIGHOULCOIN", "Gimmighoul Coin"));
        List.add(new Pair("TINYBAMBOOSHOOT", "Tiny Bamboo Shoot"));
        List.add(new Pair("BIGBAMBOOSHOOT", "Big Bamboo Shoot"));
        List.add(new Pair("ROTOMPHONE", "Rotom Phone"));
        List.add(new Pair("SCARLETBOOK", "Scarlet Book"));
        List.add(new Pair("VIOLETBOOK", "Violet Book"));
        List.add(new Pair("HEALTHMOCHI", "Health Mochi"));
        List.add(new Pair("MUSCLEMOCHI", "Muscle Mochi"));
        List.add(new Pair("RESISTMOCHI", "Resist Mochi"));
        List.add(new Pair("GENIUSMOCHI", "Genius Mochi"));
        List.add(new Pair("CLEVERMOCHI", "Clever Mochi"));
        List.add(new Pair("SWIFTMOCHI", "Swift Mochi"));
        List.add(new Pair("FRESHSTARTMOCHI", "Fresh-Start Mochi"));
        List.add(new Pair("FAIRYFEATHER", "Fairy Feather"));
        List.add(new Pair("SYRUPYAPPLE", "Syrupy Apple"));
        List.add(new Pair("UNREMARKABLETEACUP", "Unremarkable Teacup"));
        List.add(new Pair("MASTERPIECETEACUP", "Masterpiece Teacup"));
        List.add(new Pair("WELLSPRINGMASK", "Wellspring Mask"));
        List.add(new Pair("HEARTHFLAMEMASK", "Hearthflame Mask"));
        List.add(new Pair("CORNERSTONEMASK", "Cornerstone Mask"));
        List.add(new Pair("TEALMASK", "Teal Mask"));
        List.add(new Pair("METALALLOY", "Metal Alloy"));
        List.add(new Pair("INDIGODISK", "Indigo Disk"));
        List.add(new Pair("MYTHICALPECHABERRY", "Mythical Pecha Berry"));
        List.add(new Pair("SYNCHROMACHINE", "Synchro Machine"));
        List.add(new Pair("METEORITE", "Meteorite"));
        List.add(new Pair("BRIARSBOOK", "Briar's Book"));
        
        // Terastal
        List.add(new Pair("TERAORB", "Tera Orb"));
        List.add(new Pair("NORMALTERASHARD", "Normal Tera Shard"));
        List.add(new Pair("FIRETERASHARD", "Fire Tera Shard"));
        List.add(new Pair("WATERTERASHARD", "Water Tera Shard"));
        List.add(new Pair("ELECTRICTERASHARD", "Electric Tera Shard"));
        List.add(new Pair("GRASSTERASHARD", "Grass Tera Shard"));
        List.add(new Pair("ICETERASHARD", "Ice Tera Shard"));
        List.add(new Pair("FIGHTINGTERASHARD", "Fighting Tera Shard"));
        List.add(new Pair("POISONTERASHARD", "Poison Tera Shard"));
        List.add(new Pair("GROUNDTERASHARD", "Ground Tera Shard"));
        List.add(new Pair("FLYINGTERASHARD", "Flying Tera Shard"));
        List.add(new Pair("PSYCHICTERASHARD", "Psychic Tera Shard"));
        List.add(new Pair("BUGTERASHARD", "Bug Tera Shard"));
        List.add(new Pair("ROCKTERASHARD", "Rock Tera Shard"));
        List.add(new Pair("GHOSTTERASHARD", "Ghost Tera Shard"));
        List.add(new Pair("DRAGONTERASHARD", "Dragon Tera Shard"));
        List.add(new Pair("DARKTERASHARD", "Dark Tera Shard"));
        List.add(new Pair("STEELTERASHARD", "Steel Tera Shard"));
        List.add(new Pair("FAIRYTERASHARD", "Fairy Tera Shard"));
        List.add(new Pair("STELLARTERASHARD", "Stellar Tera Shard"));
        List.add(new Pair("MYSTERYTERAJEWEL", "Mystery Tera Jewel"));
        List.add(new Pair("MASTERTERAJEWEL", "Master Tera Jewel"));
        List.add(new Pair("RADIANTTERAJEWEL", "Radiant Tera Jewel"));
        List.add(new Pair("GLIMMERINGCHARM", "Glimmering Charm"));
        
        // Z-Power
        List.add(new Pair("ZRING", "Z-Ring"));
        List.add(new Pair("ZPOWERRING", "Z-Power Ring"));
        List.add(new Pair("ZBOOSTER", "Z-Booster"));
        List.add(new Pair("NORMALIUMZ", "Normalium Z"));
        List.add(new Pair("FIGHTINIUMZ", "Fightinium Z"));
        List.add(new Pair("FLYINIUMZ", "Flyinium Z"));
        List.add(new Pair("POISONIUMZ", "Poisonium Z"));
        List.add(new Pair("GROUNDIUMZ", "Groundium Z"));
        List.add(new Pair("ROCKIUMZ", "Rockium Z"));
        List.add(new Pair("BUGINIUMZ", "Buginium Z"));
        List.add(new Pair("GHOSTIUMZ", "Ghostium Z"));
        List.add(new Pair("STEELIUMZ", "Steelium Z"));
        List.add(new Pair("FIRIUMZ", "Firium Z"));
        List.add(new Pair("WATERIUMZ", "Waterium Z"));
        List.add(new Pair("GRASSIUMZ", "Grassium Z"));
        List.add(new Pair("ELECTRIUMZ", "Electrium Z"));
        List.add(new Pair("PSYCHIUMZ", "Psychium Z"));
        List.add(new Pair("ICIUMZ", "Icium Z"));
        List.add(new Pair("DRAGONIUMZ", "Dragonium Z"));
        List.add(new Pair("DARKINIUMZ", "Darkinium Z"));
        List.add(new Pair("FAIRIUMZ", "Fairium Z"));
        List.add(new Pair("PIKANIUMZ", "Pikanium Z"));
        List.add(new Pair("PIKASHUNIUMZ", "Pikashunium Z"));
        List.add(new Pair("ALORAICHIUMZ", "Aloraichium Z"));
        List.add(new Pair("EEVIUMZ", "Eevium Z"));
        List.add(new Pair("SNORLIUMZ", "Snorlium Z"));
        List.add(new Pair("MEWNIUMZ", "Mewnium Z"));
        List.add(new Pair("DECIDIUMZ", "Decidium Z"));
        List.add(new Pair("INCINIUMZ", "Incinium Z"));
        List.add(new Pair("PRIMARIUMZ", "Primarium Z"));
        List.add(new Pair("LYCANIUMZ", "Lycanium Z"));
        List.add(new Pair("MIMIKIUMZ", "Mimikium Z"));
        List.add(new Pair("KOMMONIUMZ", "Kommonium Z"));
        List.add(new Pair("TAPUNIUMZ", "Tapunium Z"));
        List.add(new Pair("SOLGANIUMZ", "Solganium Z"));
        List.add(new Pair("LUNALIUMZ", "Lunalium Z"));
        List.add(new Pair("MARSHADIUMZ", "Marshadium Z"));
        List.add(new Pair("ULTRANECROZIUMZ", "Ultranecrozium Z"));
        
        // Other
        List.add(new Pair("MARKCHARM", "Mark Charm"));
        List.add(new Pair("BOTTLECAP", "Bottle Cap"));
        List.add(new Pair("GOLDBOTTLECAP", "Gold Bottle Cap"));
        List.add(new Pair("RUSTYBOTTLECAP", "Rusty Bottle Cap"));
    }
}
