/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package showdowntotrainer;

import java.util.ArrayList;

/**
 *
 * @author codem
 */
public class MovePairs {
    public static ArrayList<Pair> List = new ArrayList<>();
    
    public void setup()
    {
        List.add(new Pair("MEGAHORN", "Megahorn"));
        List.add(new Pair("ATTACKORDER", "Attack Order"));
        List.add(new Pair("BUGBUZZ", "Bug Buzz"));
        List.add(new Pair("FIRSTIMPRESSION", "First Impression"));
        List.add(new Pair("POLLENPUFF", "Pollen Puff"));
        List.add(new Pair("LEECHLIFE", "Leech Life"));
        List.add(new Pair("LUNGE", "Lunge"));
        List.add(new Pair("XSCISSOR", "X-Scissor"));
        List.add(new Pair("SIGNALBEAM", "Signal Beam"));
        List.add(new Pair("SKITTERSMACK", "Skitter Smack"));
        List.add(new Pair("UTURN", "U-turn"));
        List.add(new Pair("STEAMROLLER", "Steamroller"));
        List.add(new Pair("BUGBITE", "Bug Bite"));
        List.add(new Pair("SILVERWIND", "Silver Wind"));
        List.add(new Pair("FELLSTINGER", "Fell Stinger"));
        List.add(new Pair("STRUGGLEBUG", "Struggle Bug"));
        List.add(new Pair("FURYCUTTER", "Fury Cutter"));
        List.add(new Pair("PINMISSILE", "Pin Missile"));
        List.add(new Pair("TWINEEDLE", "Twineedle"));
        List.add(new Pair("INFESTATION", "Infestation"));
        List.add(new Pair("DEFENDORDER", "Defend Order"));
        List.add(new Pair("HEALORDER", "Heal Order"));
        List.add(new Pair("POWDER", "Powder"));
        List.add(new Pair("QUIVERDANCE", "Quiver Dance"));
        List.add(new Pair("RAGEPOWDER", "Rage Powder"));
        List.add(new Pair("SPIDERWEB", "Spider Web"));
        List.add(new Pair("STICKYWEB", "Sticky Web"));
        List.add(new Pair("STRINGSHOT", "String Shot"));
        List.add(new Pair("TAILGLOW", "Tail Glow"));
        List.add(new Pair("HYPERSPACEFURY", "Hyperspace Fury"));
        List.add(new Pair("FOULPLAY", "Foul Play"));
        List.add(new Pair("FIERYWRATH", "Fiery Wrath"));
        List.add(new Pair("DARKESTLARIAT", "Darkest Lariat"));
        List.add(new Pair("NIGHTDAZE", "Night Daze"));
        List.add(new Pair("CRUNCH", "Crunch"));
        List.add(new Pair("DARKPULSE", "Dark Pulse"));
        List.add(new Pair("FALSESURRENDER", "False Surrender"));
        List.add(new Pair("JAWLOCK", "Jaw Lock"));
        List.add(new Pair("THROATCHOP", "Throat Chop"));
        List.add(new Pair("WICKEDBLOW", "Wicked Blow"));
        List.add(new Pair("LASHOUT", "Lash Out"));
        List.add(new Pair("NIGHTSLASH", "Night Slash"));
        List.add(new Pair("SUCKERPUNCH", "Sucker Punch"));
        List.add(new Pair("KNOCKOFF", "Knock Off"));
        List.add(new Pair("ASSURANCE", "Assurance"));
        List.add(new Pair("BITE", "Bite"));
        List.add(new Pair("BRUTALSWING", "Brutal Swing"));
        List.add(new Pair("FEINTATTACK", "Feint Attack"));
        List.add(new Pair("THIEF", "Thief"));
        List.add(new Pair("SNARL", "Snarl"));
        List.add(new Pair("PAYBACK", "Payback"));
        List.add(new Pair("PURSUIT", "Pursuit"));
        List.add(new Pair("BEATUP", "Beat Up"));
        List.add(new Pair("FLING", "Fling"));
        List.add(new Pair("POWERTRIP", "Power Trip"));
        List.add(new Pair("PUNISHMENT", "Punishment"));
        List.add(new Pair("DARKVOID", "Dark Void"));
        List.add(new Pair("EMBARGO", "Embargo"));
        List.add(new Pair("FAKETEARS", "Fake Tears"));
        List.add(new Pair("FLATTER", "Flatter"));
        List.add(new Pair("HONECLAWS", "Hone Claws"));
        List.add(new Pair("MEMENTO", "Memento"));
        List.add(new Pair("NASTYPLOT", "Nasty Plot"));
        List.add(new Pair("OBSTRUCT", "Obstruct"));
        List.add(new Pair("PARTINGSHOT", "Parting Shot"));
        List.add(new Pair("QUASH", "Quash"));
        List.add(new Pair("SNATCH", "Snatch"));
        List.add(new Pair("SWITCHEROO", "Switcheroo"));
        List.add(new Pair("TAUNT", "Taunt"));
        List.add(new Pair("TOPSYTURVY", "Topsy-Turvy"));
        List.add(new Pair("TORMENT", "Torment"));
        List.add(new Pair("ETERNABEAM", "Eternabeam"));
        List.add(new Pair("DRAGONENERGY", "Dragon Energy"));
        List.add(new Pair("ROAROFTIME", "Roar of Time"));
        List.add(new Pair("DRACOMETEOR", "Draco Meteor"));
        List.add(new Pair("OUTRAGE", "Outrage"));
        List.add(new Pair("CLANGINGSCALES", "Clanging Scales"));
        List.add(new Pair("COREENFORCER", "Core Enforcer"));
        List.add(new Pair("DRAGONRUSH", "Dragon Rush"));
        List.add(new Pair("DYNAMAXCANNON", "Dynamax Cannon"));
        List.add(new Pair("SPACIALREND", "Spacial Rend"));
        List.add(new Pair("DRAGONHAMMER", "Dragon Hammer"));
        List.add(new Pair("DRAGONPULSE", "Dragon Pulse"));
        List.add(new Pair("DRAGONCLAW", "Dragon Claw"));
        List.add(new Pair("BREAKINGSWIPE", "Breaking Swipe"));
        List.add(new Pair("DRAGONBREATH", "Dragon Breath"));
        List.add(new Pair("DRAGONTAIL", "Dragon Tail"));
        List.add(new Pair("DRAGONDARTS", "Dragon Darts"));
        List.add(new Pair("DUALCHOP", "Dual Chop"));
        List.add(new Pair("TWISTER", "Twister"));
        List.add(new Pair("SCALESHOT", "Scale Shot"));
        List.add(new Pair("DRAGONRAGE", "Dragon Rage"));
        List.add(new Pair("CLANGOROUSSOUL", "Clangorous Soul"));
        List.add(new Pair("DRAGONDANCE", "Dragon Dance"));
        List.add(new Pair("BOLTSTRIKE", "Bolt Strike"));
        List.add(new Pair("VOLTTACKLE", "Volt Tackle"));
        List.add(new Pair("ZAPCANNON", "Zap Cannon"));
        List.add(new Pair("AURAWHEEL", "Aura Wheel"));
        List.add(new Pair("THUNDER", "Thunder"));
        List.add(new Pair("FUSIONBOLT", "Fusion Bolt"));
        List.add(new Pair("PLASMAFISTS", "Plasma Fists"));
        List.add(new Pair("THUNDERBOLT", "Thunderbolt"));
        List.add(new Pair("WILDCHARGE", "Wild Charge"));
        List.add(new Pair("BOLTBEAK", "Bolt Beak"));
        List.add(new Pair("DISCHARGE", "Discharge"));
        List.add(new Pair("OVERDRIVE", "Overdrive"));
        List.add(new Pair("THUNDERCAGE", "Thunder Cage"));
        List.add(new Pair("ZINGZAP", "Zing Zap"));
        List.add(new Pair("THUNDERPUNCH", "Thunder Punch"));
        List.add(new Pair("RISINGVOLTAGE", "Rising Voltage"));
        List.add(new Pair("VOLTSWITCH", "Volt Switch"));
        List.add(new Pair("PARABOLICCHARGE", "Parabolic Charge"));
        List.add(new Pair("SPARK", "Spark"));
        List.add(new Pair("THUNDERFANG", "Thunder Fang"));
        List.add(new Pair("SHOCKWAVE", "Shock Wave"));
        List.add(new Pair("ELECTROWEB", "Electroweb"));
        List.add(new Pair("CHARGEBEAM", "Charge Beam"));
        List.add(new Pair("THUNDERSHOCK", "Thunder Shock"));
        List.add(new Pair("NUZZLE", "Nuzzle"));
        List.add(new Pair("ELECTROBALL", "Electro Ball"));
        List.add(new Pair("CHARGE", "Charge"));
        List.add(new Pair("EERIEIMPULSE", "Eerie Impulse"));
        List.add(new Pair("ELECTRICTERRAIN", "Electric Terrain"));
        List.add(new Pair("ELECTRIFY", "Electrify"));
        List.add(new Pair("IONDELUGE", "Ion Deluge"));
        List.add(new Pair("MAGNETRISE", "Magnet Rise"));
        List.add(new Pair("MAGNETICFLUX", "Magnetic Flux"));
        List.add(new Pair("THUNDERWAVE", "Thunder Wave"));
        List.add(new Pair("LIGHTOFRUIN", "Light of Ruin"));
        List.add(new Pair("FLEURCANNON", "Fleur Cannon"));
        List.add(new Pair("MISTYEXPLOSION", "Misty Explosion"));
        List.add(new Pair("MOONBLAST", "Moonblast"));
        List.add(new Pair("PLAYROUGH", "Play Rough"));
        List.add(new Pair("STRANGESTEAM", "Strange Steam"));
        List.add(new Pair("DAZZLINGGLEAM", "Dazzling Gleam"));
        List.add(new Pair("SPIRITBREAK", "Spirit Break"));
        List.add(new Pair("DRAININGKISS", "Draining Kiss"));
        List.add(new Pair("DISARMINGVOICE", "Disarming Voice"));
        List.add(new Pair("FAIRYWIND", "Fairy Wind"));
        List.add(new Pair("NATURESMADNESS", "Nature's Madness"));
        List.add(new Pair("AROMATICMIST", "Aromatic Mist"));
        List.add(new Pair("BABYDOLLEYES", "Baby-Doll Eyes"));
        List.add(new Pair("CHARM", "Charm"));
        List.add(new Pair("CRAFTYSHIELD", "Crafty Shield"));
        List.add(new Pair("DECORATE", "Decorate"));
        List.add(new Pair("FAIRYLOCK", "Fairy Lock"));
        List.add(new Pair("FLORALHEALING", "Floral Healing"));
        List.add(new Pair("FLOWERSHIELD", "Flower Shield"));
        List.add(new Pair("GEOMANCY", "Geomancy"));
        List.add(new Pair("MISTYTERRAIN", "Misty Terrain"));
        List.add(new Pair("MOONLIGHT", "Moonlight"));
        List.add(new Pair("SWEETKISS", "Sweet Kiss"));
        List.add(new Pair("FOCUSPUNCH", "Focus Punch"));
        List.add(new Pair("METEORASSAULT", "Meteor Assault"));
        List.add(new Pair("HIGHJUMPKICK", "High Jump Kick"));
        List.add(new Pair("CLOSECOMBAT", "Close Combat"));
        List.add(new Pair("FOCUSBLAST", "Focus Blast"));
        List.add(new Pair("SUPERPOWER", "Superpower"));
        List.add(new Pair("CROSSCHOP", "Cross Chop"));
        List.add(new Pair("DYNAMICPUNCH", "Dynamic Punch"));
        List.add(new Pair("FLYINGPRESS", "Flying Press"));
        List.add(new Pair("HAMMERARM", "Hammer Arm"));
        List.add(new Pair("JUMPKICK", "Jump Kick"));
        List.add(new Pair("SACREDSWORD", "Sacred Sword"));
        List.add(new Pair("THUNDEROUSKICK", "Thunderous Kick"));
        List.add(new Pair("SECRETSWORD", "Secret Sword"));
        List.add(new Pair("SKYUPPERCUT", "Sky Uppercut"));
        List.add(new Pair("AURASPHERE", "Aura Sphere"));
        List.add(new Pair("BODYPRESS", "Body Press"));
        List.add(new Pair("SUBMISSION", "Submission"));
        List.add(new Pair("BRICKBREAK", "Brick Break"));
        List.add(new Pair("DRAINPUNCH", "Drain Punch"));
        List.add(new Pair("VITALTHROW", "Vital Throw"));
        List.add(new Pair("WAKEUPSLAP", "Wake-Up Slap"));
        List.add(new Pair("LOWSWEEP", "Low Sweep"));
        List.add(new Pair("CIRCLETHROW", "Circle Throw"));
        List.add(new Pair("FORCEPALM", "Force Palm"));
        List.add(new Pair("REVENGE", "Revenge"));
        List.add(new Pair("ROLLINGKICK", "Rolling Kick"));
        List.add(new Pair("STORMTHROW", "Storm Throw"));
        List.add(new Pair("KARATECHOP", "Karate Chop"));
        List.add(new Pair("MACHPUNCH", "Mach Punch"));
        List.add(new Pair("POWERUPPUNCH", "Power-Up Punch"));
        List.add(new Pair("ROCKSMASH", "Rock Smash"));
        List.add(new Pair("VACUUMWAVE", "Vacuum Wave"));
        List.add(new Pair("DOUBLEKICK", "Double Kick"));
        List.add(new Pair("ARMTHRUST", "Arm Thrust"));
        List.add(new Pair("TRIPLEKICK", "Triple Kick"));
        List.add(new Pair("COUNTER", "Counter"));
        List.add(new Pair("FINALGAMBIT", "Final Gambit"));
        List.add(new Pair("LOWKICK", "Low Kick"));
        List.add(new Pair("REVERSAL", "Reversal"));
        List.add(new Pair("SEISMICTOSS", "Seismic Toss"));
        List.add(new Pair("BULKUP", "Bulk Up"));
        List.add(new Pair("COACHING", "Coaching"));
        List.add(new Pair("DETECT", "Detect"));
        List.add(new Pair("MATBLOCK", "Mat Block"));
        List.add(new Pair("NORETREAT", "No Retreat"));
        List.add(new Pair("OCTOLOCK", "Octolock"));
        List.add(new Pair("QUICKGUARD", "Quick Guard"));
        List.add(new Pair("VCREATE", "V-create"));
        List.add(new Pair("BLASTBURN", "Blast Burn"));
        List.add(new Pair("ERUPTION", "Eruption"));
        List.add(new Pair("MINDBLOWN", "Mind Blown"));
        List.add(new Pair("SHELLTRAP", "Shell Trap"));
        List.add(new Pair("BLUEFLARE", "Blue Flare"));
        List.add(new Pair("BURNUP", "Burn Up"));
        List.add(new Pair("OVERHEAT", "Overheat"));
        List.add(new Pair("FLAREBLITZ", "Flare Blitz"));
        List.add(new Pair("PYROBALL", "Pyro Ball"));
        List.add(new Pair("FIREBLAST", "Fire Blast"));
        List.add(new Pair("FUSIONFLARE", "Fusion Flare"));
        List.add(new Pair("INFERNO", "Inferno"));
        List.add(new Pair("MAGMASTORM", "Magma Storm"));
        List.add(new Pair("SACREDFIRE", "Sacred Fire"));
        List.add(new Pair("SEARINGSHOT", "Searing Shot"));
        List.add(new Pair("HEATWAVE", "Heat Wave"));
        List.add(new Pair("FLAMETHROWER", "Flamethrower"));
        List.add(new Pair("BLAZEKICK", "Blaze Kick"));
        List.add(new Pair("FIERYDANCE", "Fiery Dance"));
        List.add(new Pair("FIRELASH", "Fire Lash"));
        List.add(new Pair("FIREPLEDGE", "Fire Pledge"));
        List.add(new Pair("LAVAPLUME", "Lava Plume"));
        List.add(new Pair("FIREPUNCH", "Fire Punch"));
        List.add(new Pair("MYSTICALFIRE", "Mystical Fire"));
        List.add(new Pair("BURNINGJEALOUSY", "Burning Jealousy"));
        List.add(new Pair("FLAMEBURST", "Flame Burst"));
        List.add(new Pair("FIREFANG", "Fire Fang"));
        List.add(new Pair("FLAMEWHEEL", "Flame Wheel"));
        List.add(new Pair("INCINERATE", "Incinerate"));
        List.add(new Pair("FLAMECHARGE", "Flame Charge"));
        List.add(new Pair("EMBER", "Ember"));
        List.add(new Pair("FIRESPIN", "Fire Spin"));
        List.add(new Pair("HEATCRASH", "Heat Crash"));
        List.add(new Pair("SUNNYDAY", "Sunny Day"));
        List.add(new Pair("WILLOWISP", "Will-O-Wisp"));
        List.add(new Pair("SKYATTACK", "Sky Attack"));
        List.add(new Pair("BRAVEBIRD", "Brave Bird"));
        List.add(new Pair("DRAGONASCENT", "Dragon Ascent"));
        List.add(new Pair("HURRICANE", "Hurricane"));
        List.add(new Pair("AEROBLAST", "Aeroblast"));
        List.add(new Pair("BEAKBLAST", "Beak Blast"));
        List.add(new Pair("FLY", "Fly"));
        List.add(new Pair("BOUNCE", "Bounce"));
        List.add(new Pair("DRILLPECK", "Drill Peck"));
        List.add(new Pair("OBLIVIONWING", "Oblivion Wing"));
        List.add(new Pair("AIRSLASH", "Air Slash"));
        List.add(new Pair("CHATTER", "Chatter"));
        List.add(new Pair("AERIALACE", "Aerial Ace"));
        List.add(new Pair("AIRCUTTER", "Air Cutter"));
        List.add(new Pair("PLUCK", "Pluck"));
        List.add(new Pair("SKYDROP", "Sky Drop"));
        List.add(new Pair("WINGATTACK", "Wing Attack"));
        List.add(new Pair("ACROBATICS", "Acrobatics"));
        List.add(new Pair("DUALWINGBEAT", "Dual Wingbeat"));
        List.add(new Pair("GUST", "Gust"));
        List.add(new Pair("PECK", "Peck"));
        List.add(new Pair("DEFOG", "Defog"));
        List.add(new Pair("FEATHERDANCE", "Feather Dance"));
        List.add(new Pair("MIRRORMOVE", "Mirror Move"));
        List.add(new Pair("ROOST", "Roost"));
        List.add(new Pair("TAILWIND", "Tailwind"));
        List.add(new Pair("ASTRALBARRAGE", "Astral Barrage"));
        List.add(new Pair("SHADOWFORCE", "Shadow Force"));
        List.add(new Pair("POLTERGEIST", "Poltergeist"));
        List.add(new Pair("MOONGEISTBEAM", "Moongeist Beam"));
        List.add(new Pair("PHANTOMFORCE", "Phantom Force"));
        List.add(new Pair("SPECTRALTHIEF", "Spectral Thief"));
        List.add(new Pair("SHADOWBONE", "Shadow Bone"));
        List.add(new Pair("SHADOWBALL", "Shadow Ball"));
        List.add(new Pair("SPIRITSHACKLE", "Spirit Shackle"));
        List.add(new Pair("SHADOWCLAW", "Shadow Claw"));
        List.add(new Pair("HEX", "Hex"));
        List.add(new Pair("OMINOUSWIND", "Ominous Wind"));
        List.add(new Pair("SHADOWPUNCH", "Shadow Punch"));
        List.add(new Pair("SHADOWSNEAK", "Shadow Sneak"));
        List.add(new Pair("ASTONISH", "Astonish"));
        List.add(new Pair("LICK", "Lick"));
        List.add(new Pair("NIGHTSHADE", "Night Shade"));
        List.add(new Pair("CONFUSERAY", "Confuse Ray"));
        List.add(new Pair("CURSE", "Curse"));
        List.add(new Pair("DESTINYBOND", "Destiny Bond"));
        List.add(new Pair("GRUDGE", "Grudge"));
        List.add(new Pair("NIGHTMARE", "Nightmare"));
        List.add(new Pair("SPITE", "Spite"));
        List.add(new Pair("TRICKORTREAT", "Trick-or-Treat"));
        List.add(new Pair("FRENZYPLANT", "Frenzy Plant"));
        List.add(new Pair("LEAFSTORM", "Leaf Storm"));
        List.add(new Pair("SOLARBLADE", "Solar Blade"));
        List.add(new Pair("PETALDANCE", "Petal Dance"));
        List.add(new Pair("POWERWHIP", "Power Whip"));
        List.add(new Pair("SEEDFLARE", "Seed Flare"));
        List.add(new Pair("SOLARBEAM", "Solar Beam"));
        List.add(new Pair("WOODHAMMER", "Wood Hammer"));
        List.add(new Pair("ENERGYBALL", "Energy Ball"));
        List.add(new Pair("LEAFBLADE", "Leaf Blade"));
        List.add(new Pair("PETALBLIZZARD", "Petal Blizzard"));
        List.add(new Pair("APPLEACID", "Apple Acid"));
        List.add(new Pair("DRUMBEATING", "Drum Beating"));
        List.add(new Pair("GRASSPLEDGE", "Grass Pledge"));
        List.add(new Pair("GRAVAPPLE", "Grav Apple"));
        List.add(new Pair("SEEDBOMB", "Seed Bomb"));
        List.add(new Pair("GIGADRAIN", "Giga Drain"));
        List.add(new Pair("HORNLEECH", "Horn Leech"));
        List.add(new Pair("GRASSYGLIDE", "Grassy Glide"));
        List.add(new Pair("TROPKICK", "Trop Kick"));
        List.add(new Pair("LEAFTORNADO", "Leaf Tornado"));
        List.add(new Pair("MAGICALLEAF", "Magical Leaf"));
        List.add(new Pair("NEEDLEARM", "Needle Arm"));
        List.add(new Pair("RAZORLEAF", "Razor Leaf"));
        List.add(new Pair("VINEWHIP", "Vine Whip"));
        List.add(new Pair("BRANCHPOKE", "Branch Poke"));
        List.add(new Pair("LEAFAGE", "Leafage"));
        List.add(new Pair("MEGADRAIN", "Mega Drain"));
        List.add(new Pair("SNAPTRAP", "Snap Trap"));
        List.add(new Pair("BULLETSEED", "Bullet Seed"));
        List.add(new Pair("ABSORB", "Absorb"));
        List.add(new Pair("GRASSKNOT", "Grass Knot"));
        List.add(new Pair("AROMATHERAPY", "Aromatherapy"));
        List.add(new Pair("COTTONGUARD", "Cotton Guard"));
        List.add(new Pair("COTTONSPORE", "Cotton Spore"));
        List.add(new Pair("FORESTSCURSE", "Forest's Curse"));
        List.add(new Pair("GRASSWHISTLE", "Grass Whistle"));
        List.add(new Pair("GRASSYTERRAIN", "Grassy Terrain"));
        List.add(new Pair("INGRAIN", "Ingrain"));
        List.add(new Pair("JUNGLEHEALING", "Jungle Healing"));
        List.add(new Pair("LEECHSEED", "Leech Seed"));
        List.add(new Pair("SLEEPPOWDER", "Sleep Powder"));
        List.add(new Pair("SPIKYSHIELD", "Spiky Shield"));
        List.add(new Pair("SPORE", "Spore"));
        List.add(new Pair("STRENGTHSAP", "Strength Sap"));
        List.add(new Pair("STUNSPORE", "Stun Spore"));
        List.add(new Pair("SYNTHESIS", "Synthesis"));
        List.add(new Pair("WORRYSEED", "Worry Seed"));
        List.add(new Pair("PRECIPICEBLADES", "Precipice Blades"));
        List.add(new Pair("EARTHQUAKE", "Earthquake"));
        List.add(new Pair("HIGHHORSEPOWER", "High Horsepower"));
        List.add(new Pair("EARTHPOWER", "Earth Power"));
        List.add(new Pair("LANDSWRATH", "Land's Wrath"));
        List.add(new Pair("THOUSANDARROWS", "Thousand Arrows"));
        List.add(new Pair("THOUSANDWAVES", "Thousand Waves"));
        List.add(new Pair("DIG", "Dig"));
        List.add(new Pair("DRILLRUN", "Drill Run"));
        List.add(new Pair("STOMPINGTANTRUM", "Stomping Tantrum"));
        List.add(new Pair("SCORCHINGSANDS", "Scorching Sands"));
        List.add(new Pair("BONECLUB", "Bone Club"));
        List.add(new Pair("MUDBOMB", "Mud Bomb"));
        List.add(new Pair("BULLDOZE", "Bulldoze"));
        List.add(new Pair("MUDSHOT", "Mud Shot"));
        List.add(new Pair("BONEMERANG", "Bonemerang"));
        List.add(new Pair("SANDTOMB", "Sand Tomb"));
        List.add(new Pair("BONERUSH", "Bone Rush"));
        List.add(new Pair("MUDSLAP", "Mud-Slap"));
        List.add(new Pair("FISSURE", "Fissure"));
        List.add(new Pair("MAGNITUDE", "Magnitude"));
        List.add(new Pair("MUDSPORT", "Mud Sport"));
        List.add(new Pair("ROTOTILLER", "Rototiller"));
        List.add(new Pair("SANDATTACK", "Sand Attack"));
        List.add(new Pair("SHOREUP", "Shore Up"));
        List.add(new Pair("SPIKES", "Spikes"));
        List.add(new Pair("FREEZESHOCK", "Freeze Shock"));
        List.add(new Pair("ICEBURN", "Ice Burn"));
        List.add(new Pair("GLACIALLANCE", "Glacial Lance"));
        List.add(new Pair("BLIZZARD", "Blizzard"));
        List.add(new Pair("ICEHAMMER", "Ice Hammer"));
        List.add(new Pair("ICEBEAM", "Ice Beam"));
        List.add(new Pair("ICICLECRASH", "Icicle Crash"));
        List.add(new Pair("ICEPUNCH", "Ice Punch"));
        List.add(new Pair("FREEZEDRY", "Freeze-Dry"));
        List.add(new Pair("AURORABEAM", "Aurora Beam"));
        List.add(new Pair("GLACIATE", "Glaciate"));
        List.add(new Pair("ICEFANG", "Ice Fang"));
        List.add(new Pair("AVALANCHE", "Avalanche"));
        List.add(new Pair("FROSTBREATH", "Frost Breath"));
        List.add(new Pair("ICYWIND", "Icy Wind"));
        List.add(new Pair("ICESHARD", "Ice Shard"));
        List.add(new Pair("POWDERSNOW", "Powder Snow"));
        List.add(new Pair("ICEBALL", "Ice Ball"));
        List.add(new Pair("ICICLESPEAR", "Icicle Spear"));
        List.add(new Pair("TRIPLEAXEL", "Triple Axel"));
        List.add(new Pair("SHEERCOLD", "Sheer Cold"));
        List.add(new Pair("AURORAVEIL", "Aurora Veil"));
        List.add(new Pair("HAIL", "Hail"));
        List.add(new Pair("HAZE", "Haze"));
        List.add(new Pair("MIST", "Mist"));
        List.add(new Pair("EXPLOSION", "Explosion"));
        List.add(new Pair("SELFDESTRUCT", "Self-Destruct"));
        List.add(new Pair("GIGAIMPACT", "Giga Impact"));
        List.add(new Pair("HYPERBEAM", "Hyper Beam"));
        List.add(new Pair("BOOMBURST", "Boomburst"));
        List.add(new Pair("LASTRESORT", "Last Resort"));
        List.add(new Pair("SKULLBASH", "Skull Bash"));
        List.add(new Pair("DOUBLEEDGE", "Double-Edge"));
        List.add(new Pair("HEADCHARGE", "Head Charge"));
        List.add(new Pair("MEGAKICK", "Mega Kick"));
        List.add(new Pair("MULTIATTACK", "Multi-Attack"));
        List.add(new Pair("TECHNOBLAST", "Techno Blast"));
        List.add(new Pair("THRASH", "Thrash"));
        List.add(new Pair("EGGBOMB", "Egg Bomb"));
        List.add(new Pair("JUDGMENT", "Judgment"));
        List.add(new Pair("HYPERVOICE", "Hyper Voice"));
        List.add(new Pair("REVELATIONDANCE", "Revelation Dance"));
        List.add(new Pair("ROCKCLIMB", "Rock Climb"));
        List.add(new Pair("TAKEDOWN", "Take Down"));
        List.add(new Pair("UPROAR", "Uproar"));
        List.add(new Pair("BODYSLAM", "Body Slam"));
        List.add(new Pair("EXTREMESPEED", "Extreme Speed"));
        List.add(new Pair("HYPERFANG", "Hyper Fang"));
        List.add(new Pair("MEGAPUNCH", "Mega Punch"));
        List.add(new Pair("RAZORWIND", "Razor Wind"));
        List.add(new Pair("SLAM", "Slam"));
        List.add(new Pair("STRENGTH", "Strength"));
        List.add(new Pair("TRIATTACK", "Tri Attack"));
        List.add(new Pair("CRUSHCLAW", "Crush Claw"));
        List.add(new Pair("RELICSONG", "Relic Song"));
        List.add(new Pair("CHIPAWAY", "Chip Away"));
        List.add(new Pair("DIZZYPUNCH", "Dizzy Punch"));
        List.add(new Pair("FACADE", "Facade"));
        List.add(new Pair("HEADBUTT", "Headbutt"));
        List.add(new Pair("RETALIATE", "Retaliate"));
        List.add(new Pair("SECRETPOWER", "Secret Power"));
        List.add(new Pair("SLASH", "Slash"));
        List.add(new Pair("SMELLINGSALTS", "Smelling Salts"));
        List.add(new Pair("HORNATTACK", "Horn Attack"));
        List.add(new Pair("STOMP", "Stomp"));
        List.add(new Pair("COVET", "Covet"));
        List.add(new Pair("HIDDENPOWER", "Hidden Power"));
        List.add(new Pair("ROUND", "Round"));
        List.add(new Pair("SWIFT", "Swift"));
        List.add(new Pair("VISEGRIP", "Vise Grip"));
        List.add(new Pair("CUT", "Cut"));
        List.add(new Pair("RAPIDSPIN", "Rapid Spin"));
        List.add(new Pair("SNORE", "Snore"));
        List.add(new Pair("TERRAINPULSE", "Terrain Pulse"));
        List.add(new Pair("WEATHERBALL", "Weather Ball"));
        List.add(new Pair("ECHOEDVOICE", "Echoed Voice"));
        List.add(new Pair("FAKEOUT", "Fake Out"));
        List.add(new Pair("FALSESWIPE", "False Swipe"));
        List.add(new Pair("HOLDBACK", "Hold Back"));
        List.add(new Pair("PAYDAY", "Pay Day"));
        List.add(new Pair("POUND", "Pound"));
        List.add(new Pair("QUICKATTACK", "Quick Attack"));
        List.add(new Pair("SCRATCH", "Scratch"));
        List.add(new Pair("TACKLE", "Tackle"));
        List.add(new Pair("DOUBLEHIT", "Double Hit"));
        List.add(new Pair("FEINT", "Feint"));
        List.add(new Pair("TAILSLAP", "Tail Slap"));
        List.add(new Pair("RAGE", "Rage"));
        List.add(new Pair("SPIKECANNON", "Spike Cannon"));
        List.add(new Pair("COMETPUNCH", "Comet Punch"));
        List.add(new Pair("FURYSWIPES", "Fury Swipes"));
        List.add(new Pair("BARRAGE", "Barrage"));
        List.add(new Pair("BIND", "Bind"));
        List.add(new Pair("DOUBLESLAP", "Double Slap"));
        List.add(new Pair("FURYATTACK", "Fury Attack"));
        List.add(new Pair("WRAP", "Wrap"));
        List.add(new Pair("CONSTRICT", "Constrict"));
        List.add(new Pair("BIDE", "Bide"));
        List.add(new Pair("CRUSHGRIP", "Crush Grip"));
        List.add(new Pair("ENDEAVOR", "Endeavor"));
        List.add(new Pair("FLAIL", "Flail"));
        List.add(new Pair("FRUSTRATION", "Frustration"));
        List.add(new Pair("GUILLOTINE", "Guillotine"));
        List.add(new Pair("HORNDRILL", "Horn Drill"));
        List.add(new Pair("NATURALGIFT", "Natural Gift"));
        List.add(new Pair("PRESENT", "Present"));
        List.add(new Pair("RETURN", "Return"));
        List.add(new Pair("SONICBOOM", "Sonic Boom"));
        List.add(new Pair("SPITUP", "Spit Up"));
        List.add(new Pair("SUPERFANG", "Super Fang"));
        List.add(new Pair("TRUMPCARD", "Trump Card"));
        List.add(new Pair("WRINGOUT", "Wring Out"));
        List.add(new Pair("ACUPRESSURE", "Acupressure"));
        List.add(new Pair("AFTERYOU", "After You"));
        List.add(new Pair("ASSIST", "Assist"));
        List.add(new Pair("ATTRACT", "Attract"));
        List.add(new Pair("BATONPASS", "Baton Pass"));
        List.add(new Pair("BELLYDRUM", "Belly Drum"));
        List.add(new Pair("BESTOW", "Bestow"));
        List.add(new Pair("BLOCK", "Block"));
        List.add(new Pair("CAMOUFLAGE", "Camouflage"));
        List.add(new Pair("CAPTIVATE", "Captivate"));
        List.add(new Pair("CELEBRATE", "Celebrate"));
        List.add(new Pair("CONFIDE", "Confide"));
        List.add(new Pair("CONVERSION", "Conversion"));
        List.add(new Pair("CONVERSION2", "Conversion 2"));
        List.add(new Pair("COPYCAT", "Copycat"));
        List.add(new Pair("COURTCHANGE", "Court Change"));
        List.add(new Pair("DEFENSECURL", "Defense Curl"));
        List.add(new Pair("DISABLE", "Disable"));
        List.add(new Pair("DOUBLETEAM", "Double Team"));
        List.add(new Pair("ENCORE", "Encore"));
        List.add(new Pair("ENDURE", "Endure"));
        List.add(new Pair("ENTRAINMENT", "Entrainment"));
        List.add(new Pair("FLASH", "Flash"));
        List.add(new Pair("FOCUSENERGY", "Focus Energy"));
        List.add(new Pair("FOLLOWME", "Follow Me"));
        List.add(new Pair("FORESIGHT", "Foresight"));
        List.add(new Pair("GLARE", "Glare"));
        List.add(new Pair("GROWL", "Growl"));
        List.add(new Pair("GROWTH", "Growth"));
        List.add(new Pair("HAPPYHOUR", "Happy Hour"));
        List.add(new Pair("HARDEN", "Harden"));
        List.add(new Pair("HEALBELL", "Heal Bell"));
        List.add(new Pair("HELPINGHAND", "Helping Hand"));
        List.add(new Pair("HOLDHANDS", "Hold Hands"));
        List.add(new Pair("HOWL", "Howl"));
        List.add(new Pair("LASERFOCUS", "Laser Focus"));
        List.add(new Pair("LEER", "Leer"));
        List.add(new Pair("LOCKON", "Lock-On"));
        List.add(new Pair("LOVELYKISS", "Lovely Kiss"));
        List.add(new Pair("LUCKYCHANT", "Lucky Chant"));
        List.add(new Pair("MEFIRST", "Me First"));
        List.add(new Pair("MEANLOOK", "Mean Look"));
        List.add(new Pair("METRONOME", "Metronome"));
        List.add(new Pair("MILKDRINK", "Milk Drink"));
        List.add(new Pair("MIMIC", "Mimic"));
        List.add(new Pair("MINDREADER", "Mind Reader"));
        List.add(new Pair("MINIMIZE", "Minimize"));
        List.add(new Pair("MORNINGSUN", "Morning Sun"));
        List.add(new Pair("NATUREPOWER", "Nature Power"));
        List.add(new Pair("NOBLEROAR", "Noble Roar"));
        List.add(new Pair("ODORSLEUTH", "Odor Sleuth"));
        List.add(new Pair("PAINSPLIT", "Pain Split"));
        List.add(new Pair("PERISHSONG", "Perish Song"));
        List.add(new Pair("PLAYNICE", "Play Nice"));
        List.add(new Pair("PROTECT", "Protect"));
        List.add(new Pair("PSYCHUP", "Psych Up"));
        List.add(new Pair("RECOVER", "Recover"));
        List.add(new Pair("RECYCLE", "Recycle"));
        List.add(new Pair("REFLECTTYPE", "Reflect Type"));
        List.add(new Pair("REFRESH", "Refresh"));
        List.add(new Pair("ROAR", "Roar"));
        List.add(new Pair("SAFEGUARD", "Safeguard"));
        List.add(new Pair("SCARYFACE", "Scary Face"));
        List.add(new Pair("SCREECH", "Screech"));
        List.add(new Pair("SHARPEN", "Sharpen"));
        List.add(new Pair("SHELLSMASH", "Shell Smash"));
        List.add(new Pair("SIMPLEBEAM", "Simple Beam"));
        List.add(new Pair("SING", "Sing"));
        List.add(new Pair("SKETCH", "Sketch"));
        List.add(new Pair("SLACKOFF", "Slack Off"));
        List.add(new Pair("SLEEPTALK", "Sleep Talk"));
        List.add(new Pair("SMOKESCREEN", "Smokescreen"));
        List.add(new Pair("SOFTBOILED", "Soft-Boiled"));
        List.add(new Pair("SPLASH", "Splash"));
        List.add(new Pair("SPOTLIGHT", "Spotlight"));
        List.add(new Pair("STOCKPILE", "Stockpile"));
        List.add(new Pair("STUFFCHEEKS", "Stuff Cheeks"));
        List.add(new Pair("SUBSTITUTE", "Substitute"));
        List.add(new Pair("SUPERSONIC", "Supersonic"));
        List.add(new Pair("SWAGGER", "Swagger"));
        List.add(new Pair("SWALLOW", "Swallow"));
        List.add(new Pair("SWEETSCENT", "Sweet Scent"));
        List.add(new Pair("SWORDSDANCE", "Swords Dance"));
        List.add(new Pair("TAILWHIP", "Tail Whip"));
        List.add(new Pair("TEARFULLOOK", "Tearful Look"));
        List.add(new Pair("TEATIME", "Teatime"));
        List.add(new Pair("TEETERDANCE", "Teeter Dance"));
        List.add(new Pair("TICKLE", "Tickle"));
        List.add(new Pair("TRANSFORM", "Transform"));
        List.add(new Pair("WHIRLWIND", "Whirlwind"));
        List.add(new Pair("WISH", "Wish"));
        List.add(new Pair("WORKUP", "Work Up"));
        List.add(new Pair("YAWN", "Yawn"));
        List.add(new Pair("BELCH", "Belch"));
        List.add(new Pair("GUNKSHOT", "Gunk Shot"));
        List.add(new Pair("SLUDGEWAVE", "Sludge Wave"));
        List.add(new Pair("SHELLSIDEARM", "Shell Side Arm"));
        List.add(new Pair("SLUDGEBOMB", "Sludge Bomb"));
        List.add(new Pair("POISONJAB", "Poison Jab"));
        List.add(new Pair("CROSSPOISON", "Cross Poison"));
        List.add(new Pair("SLUDGE", "Sludge"));
        List.add(new Pair("VENOSHOCK", "Venoshock"));
        List.add(new Pair("CLEARSMOG", "Clear Smog"));
        List.add(new Pair("POISONFANG", "Poison Fang"));
        List.add(new Pair("POISONTAIL", "Poison Tail"));
        List.add(new Pair("ACID", "Acid"));
        List.add(new Pair("ACIDSPRAY", "Acid Spray"));
        List.add(new Pair("SMOG", "Smog"));
        List.add(new Pair("POISONSTING", "Poison Sting"));
        List.add(new Pair("ACIDARMOR", "Acid Armor"));
        List.add(new Pair("BANEFULBUNKER", "Baneful Bunker"));
        List.add(new Pair("COIL", "Coil"));
        List.add(new Pair("CORROSIVEGAS", "Corrosive Gas"));
        List.add(new Pair("GASTROACID", "Gastro Acid"));
        List.add(new Pair("POISONGAS", "Poison Gas"));
        List.add(new Pair("POISONPOWDER", "Poison Powder"));
        List.add(new Pair("PURIFY", "Purify"));
        List.add(new Pair("TOXIC", "Toxic"));
        List.add(new Pair("TOXICSPIKES", "Toxic Spikes"));
        List.add(new Pair("TOXICTHREAD", "Toxic Thread"));
        List.add(new Pair("VENOMDRENCH", "Venom Drench"));
        List.add(new Pair("PRISMATICLASER", "Prismatic Laser"));
        List.add(new Pair("PSYCHOBOOST", "Psycho Boost"));
        List.add(new Pair("FUTURESIGHT", "Future Sight"));
        List.add(new Pair("SYNCHRONOISE", "Synchronoise"));
        List.add(new Pair("DREAMEATER", "Dream Eater"));
        List.add(new Pair("PHOTONGEYSER", "Photon Geyser"));
        List.add(new Pair("PSYSTRIKE", "Psystrike"));
        List.add(new Pair("FREEZINGGLARE", "Freezing Glare"));
        List.add(new Pair("PSYCHIC", "Psychic"));
        List.add(new Pair("PSYCHICFANGS", "Psychic Fangs"));
        List.add(new Pair("EERIESPELL", "Eerie Spell"));
        List.add(new Pair("EXPANDINGFORCE", "Expanding Force"));
        List.add(new Pair("EXTRASENSORY", "Extrasensory"));
        List.add(new Pair("HYPERSPACEHOLE", "Hyperspace Hole"));
        List.add(new Pair("PSYSHOCK", "Psyshock"));
        List.add(new Pair("ZENHEADBUTT", "Zen Headbutt"));
        List.add(new Pair("LUSTERPURGE", "Luster Purge"));
        List.add(new Pair("MISTBALL", "Mist Ball"));
        List.add(new Pair("PSYCHOCUT", "Psycho Cut"));
        List.add(new Pair("PSYBEAM", "Psybeam"));
        List.add(new Pair("HEARTSTAMP", "Heart Stamp"));
        List.add(new Pair("CONFUSION", "Confusion"));
        List.add(new Pair("STOREDPOWER", "Stored Power"));
        List.add(new Pair("MIRRORCOAT", "Mirror Coat"));
        List.add(new Pair("PSYWAVE", "Psywave"));
        List.add(new Pair("AGILITY", "Agility"));
        List.add(new Pair("ALLYSWITCH", "Ally Switch"));
        List.add(new Pair("AMNESIA", "Amnesia"));
        List.add(new Pair("BARRIER", "Barrier"));
        List.add(new Pair("CALMMIND", "Calm Mind"));
        List.add(new Pair("COSMICPOWER", "Cosmic Power"));
        List.add(new Pair("GRAVITY", "Gravity"));
        List.add(new Pair("GUARDSPLIT", "Guard Split"));
        List.add(new Pair("GUARDSWAP", "Guard Swap"));
        List.add(new Pair("HEALBLOCK", "Heal Block"));
        List.add(new Pair("HEALPULSE", "Heal Pulse"));
        List.add(new Pair("HEALINGWISH", "Healing Wish"));
        List.add(new Pair("HEARTSWAP", "Heart Swap"));
        List.add(new Pair("HYPNOSIS", "Hypnosis"));
        List.add(new Pair("IMPRISON", "Imprison"));
        List.add(new Pair("INSTRUCT", "Instruct"));
        List.add(new Pair("KINESIS", "Kinesis"));
        List.add(new Pair("LIGHTSCREEN", "Light Screen"));
        List.add(new Pair("LUNARDANCE", "Lunar Dance"));
        List.add(new Pair("MAGICCOAT", "Magic Coat"));
        List.add(new Pair("MAGICPOWDER", "Magic Powder"));
        List.add(new Pair("MAGICROOM", "Magic Room"));
        List.add(new Pair("MEDITATE", "Meditate"));
        List.add(new Pair("MIRACLEEYE", "Miracle Eye"));
        List.add(new Pair("POWERSPLIT", "Power Split"));
        List.add(new Pair("POWERSWAP", "Power Swap"));
        List.add(new Pair("POWERTRICK", "Power Trick"));
        List.add(new Pair("PSYCHICTERRAIN", "Psychic Terrain"));
        List.add(new Pair("PSYCHOSHIFT", "Psycho Shift"));
        List.add(new Pair("REFLECT", "Reflect"));
        List.add(new Pair("REST", "Rest"));
        List.add(new Pair("ROLEPLAY", "Role Play"));
        List.add(new Pair("SKILLSWAP", "Skill Swap"));
        List.add(new Pair("SPEEDSWAP", "Speed Swap"));
        List.add(new Pair("TELEKINESIS", "Telekinesis"));
        List.add(new Pair("TELEPORT", "Teleport"));
        List.add(new Pair("TRICK", "Trick"));
        List.add(new Pair("TRICKROOM", "Trick Room"));
        List.add(new Pair("WONDERROOM", "Wonder Room"));
        List.add(new Pair("HEADSMASH", "Head Smash"));
        List.add(new Pair("ROCKWRECKER", "Rock Wrecker"));
        List.add(new Pair("METEORBEAM", "Meteor Beam"));
        List.add(new Pair("DIAMONDSTORM", "Diamond Storm"));
        List.add(new Pair("STONEEDGE", "Stone Edge"));
        List.add(new Pair("POWERGEM", "Power Gem"));
        List.add(new Pair("ROCKSLIDE", "Rock Slide"));
        List.add(new Pair("ANCIENTPOWER", "Ancient Power"));
        List.add(new Pair("ROCKTOMB", "Rock Tomb"));
        List.add(new Pair("ROCKTHROW", "Rock Throw"));
        List.add(new Pair("SMACKDOWN", "Smack Down"));
        List.add(new Pair("ACCELEROCK", "Accelerock"));
        List.add(new Pair("ROLLOUT", "Rollout"));
        List.add(new Pair("ROCKBLAST", "Rock Blast"));
        List.add(new Pair("ROCKPOLISH", "Rock Polish"));
        List.add(new Pair("SANDSTORM", "Sandstorm"));
        List.add(new Pair("STEALTHROCK", "Stealth Rock"));
        List.add(new Pair("TARSHOT", "Tar Shot"));
        List.add(new Pair("WIDEGUARD", "Wide Guard"));
        List.add(new Pair("DOOMDESIRE", "Doom Desire"));
        List.add(new Pair("STEELBEAM", "Steel Beam"));
        List.add(new Pair("STEELROLLER", "Steel Roller"));
        List.add(new Pair("BEHEMOTHBASH", "Behemoth Bash"));
        List.add(new Pair("BEHEMOTHBLADE", "Behemoth Blade"));
        List.add(new Pair("IRONTAIL", "Iron Tail"));
        List.add(new Pair("SUNSTEELSTRIKE", "Sunsteel Strike"));
        List.add(new Pair("METEORMASH", "Meteor Mash"));
        List.add(new Pair("ANCHORSHOT", "Anchor Shot"));
        List.add(new Pair("FLASHCANNON", "Flash Cannon"));
        List.add(new Pair("IRONHEAD", "Iron Head"));
        List.add(new Pair("SMARTSTRIKE", "Smart Strike"));
        List.add(new Pair("STEELWING", "Steel Wing"));
        List.add(new Pair("DOUBLEIRONBASH", "Double Iron Bash"));
        List.add(new Pair("MIRRORSHOT", "Mirror Shot"));
        List.add(new Pair("MAGNETBOMB", "Magnet Bomb"));
        List.add(new Pair("GEARGRIND", "Gear Grind"));
        List.add(new Pair("METALCLAW", "Metal Claw"));
        List.add(new Pair("BULLETPUNCH", "Bullet Punch"));
        List.add(new Pair("GYROBALL", "Gyro Ball"));
        List.add(new Pair("HEAVYSLAM", "Heavy Slam"));
        List.add(new Pair("METALBURST", "Metal Burst"));
        List.add(new Pair("AUTOTOMIZE", "Autotomize"));
        List.add(new Pair("GEARUP", "Gear Up"));
        List.add(new Pair("IRONDEFENSE", "Iron Defense"));
        List.add(new Pair("KINGSSHIELD", "King's Shield"));
        List.add(new Pair("METALSOUND", "Metal Sound"));
        List.add(new Pair("SHIFTGEAR", "Shift Gear"));
        List.add(new Pair("HYDROCANNON", "Hydro Cannon"));
        List.add(new Pair("WATERSPOUT", "Water Spout"));
        List.add(new Pair("HYDROPUMP", "Hydro Pump"));
        List.add(new Pair("ORIGINPULSE", "Origin Pulse"));
        List.add(new Pair("STEAMERUPTION", "Steam Eruption"));
        List.add(new Pair("CRABHAMMER", "Crabhammer"));
        List.add(new Pair("AQUATAIL", "Aqua Tail"));
        List.add(new Pair("MUDDYWATER", "Muddy Water"));
        List.add(new Pair("SPARKLINGARIA", "Sparkling Aria"));
        List.add(new Pair("SURF", "Surf"));
        List.add(new Pair("FISHIOUSREND", "Fishious Rend"));
        List.add(new Pair("LIQUIDATION", "Liquidation"));
        List.add(new Pair("DIVE", "Dive"));
        List.add(new Pair("SCALD", "Scald"));
        List.add(new Pair("SNIPESHOT", "Snipe Shot"));
        List.add(new Pair("WATERPLEDGE", "Water Pledge"));
        List.add(new Pair("WATERFALL", "Waterfall"));
        List.add(new Pair("RAZORSHELL", "Razor Shell"));
        List.add(new Pair("BRINE", "Brine"));
        List.add(new Pair("BUBBLEBEAM", "Bubble Beam"));
        List.add(new Pair("OCTAZOOKA", "Octazooka"));
        List.add(new Pair("FLIPTURN", "Flip Turn"));
        List.add(new Pair("WATERPULSE", "Water Pulse"));
        List.add(new Pair("AQUAJET", "Aqua Jet"));
        List.add(new Pair("BUBBLE", "Bubble"));
        List.add(new Pair("WATERGUN", "Water Gun"));
        List.add(new Pair("CLAMP", "Clamp"));
        List.add(new Pair("WHIRLPOOL", "Whirlpool"));
        List.add(new Pair("SURGINGSTRIKES", "Surging Strikes"));
        List.add(new Pair("WATERSHURIKEN", "Water Shuriken"));
        List.add(new Pair("AQUARING", "Aqua Ring"));
        List.add(new Pair("LIFEDEW", "Life Dew"));
        List.add(new Pair("RAINDANCE", "Rain Dance"));
        List.add(new Pair("SOAK", "Soak"));
        List.add(new Pair("WATERSPORT", "Water Sport"));
        List.add(new Pair("WITHDRAW", "Withdraw"));
        
        List.add(new Pair("DIRECLAW", "Dire Claw"));
        List.add(new Pair("SPRINGTIDESTORM", "Springtide Storm"));
        List.add(new Pair("RAGINGFURY", "Raging Fury"));
        List.add(new Pair("WAVECRASH", "Wave Crash"));
        List.add(new Pair("CHLOROBLAST", "Chloroblast"));
        List.add(new Pair("MOUNTAINGALE", "Mountain Gale"));
        List.add(new Pair("HEADLONGRUSH", "Headlong Rush"));
        List.add(new Pair("BARBBARRAGE", "Barb Barrage"));
        List.add(new Pair("ESPERWING", "Esper Wing"));
        List.add(new Pair("BITTERMALICE", "Bitter Malice"));
        List.add(new Pair("TRIPLEARROWS", "Triple Arrows"));
        List.add(new Pair("BLEAKWINDSTORM", "Bleakwind Storm"));
        List.add(new Pair("WILDBOLTSTORM", "Wildbolt Storm"));
        List.add(new Pair("SANDSEARSTORM", "Sandsear Storm"));
        List.add(new Pair("LUNARBLESSING", "Lunar Blessing"));
        List.add(new Pair("PSYSHIELDBASH", "Psyshield Bash"));
        List.add(new Pair("POWERSHIFT", "Power Shift"));
        List.add(new Pair("STONEAXE", "Stone Axe"));
        List.add(new Pair("MYSTICALPOWER", "Mystical Power"));
        List.add(new Pair("VICTORYDANCE", "Victory Dance"));
        List.add(new Pair("SHELTER", "Shelter"));
        List.add(new Pair("INFERNALPARADE", "Infernal Parade"));
        List.add(new Pair("CEASELESSEDGE", "Ceaseless Edge"));
        List.add(new Pair("TAKEHEART", "Take Heart"));
        List.add(new Pair("AQUACUTTER", "Aqua Cutter"));
        List.add(new Pair("AQUASTEP", "Aqua Step"));
        List.add(new Pair("ARMORCANNON", "Armor Cannon"));
        List.add(new Pair("AXEKICK", "Axe Kick"));
        List.add(new Pair("BITTERBLADE", "Bitter Blade"));
        List.add(new Pair("BLAZINGTORQUE", "Blazing Torque"));
        List.add(new Pair("CHILLINGWATER", "Chilling Water"));
        List.add(new Pair("CHILLYRECEPTION", "Chilly Reception"));
        List.add(new Pair("COLLISIONCOURSE", "Collision Course"));
        List.add(new Pair("COMBATTORQUE", "Combat Torque"));
        List.add(new Pair("COMEUPPANCE", "Comeuppance"));
        List.add(new Pair("DOODLE", "Doodle"));
        List.add(new Pair("DOUBLESHOCK", "Double Shock"));
        List.add(new Pair("ELECTRODRIFT", "Electro Drift"));
        List.add(new Pair("FILLETAWAY", "Fillet Away"));
        List.add(new Pair("FLOWERTRICK", "Flower Trick"));
        List.add(new Pair("GIGATONHAMMER", "Gigaton Hammer"));
        List.add(new Pair("GLAIVERUSH", "Glaive Rush"));
        List.add(new Pair("HYPERDRILL", "Hyper Drill"));
        List.add(new Pair("ICESPINNER", "Ice Spinner"));
        List.add(new Pair("JETPUNCH", "Jet Punch"));
        List.add(new Pair("KOWTOWCLEAVE", "Kowtow Cleave"));
        List.add(new Pair("LASTRESPECTS", "Last Respects"));
        List.add(new Pair("LUMINACRASH", "Lumina Crash"));
        List.add(new Pair("MAGICALTORQUE", "Magical Torque"));
        List.add(new Pair("MAKEITRAIN", "Make It Rain"));
        List.add(new Pair("MORTALSPIN", "Mortal Spin"));
        List.add(new Pair("NOXIOUSTORQUE", "Noxious Torque"));
        List.add(new Pair("ORDERUP", "Order Up"));
        List.add(new Pair("POPULATIONBOMB", "Population Bomb"));
        List.add(new Pair("POUNCE", "Pounce"));
        List.add(new Pair("RAGEFIST", "Rage Fist"));
        List.add(new Pair("RAGINGBULL", "Raging Bull"));
        List.add(new Pair("REVIVALBLESSING", "Revival Blessing"));
        List.add(new Pair("RUINATION", "Ruination"));
        List.add(new Pair("SALTCURE", "Salt Cure"));
        List.add(new Pair("SHEDTAIL", "Shed Tail"));
        List.add(new Pair("SILKTRAP", "Silk Trap"));
        List.add(new Pair("SNOWSCAPE", "Snowscape"));
        List.add(new Pair("SPICYEXTRACT", "Spicy Extract"));
        List.add(new Pair("SPINOUT", "Spin Out"));
        List.add(new Pair("TIDYUP", "Tidy Up"));
        List.add(new Pair("TORCHSONG", "Torch Song"));
        List.add(new Pair("TRAILBLAZE", "Trailblaze"));
        List.add(new Pair("TRIPLEDIVE", "Triple Dive"));
        List.add(new Pair("TWINBEAM", "Twin Beam"));
        List.add(new Pair("WICKEDTORQUE", "Wicked Torque"));
        List.add(new Pair("HYDROSTEAM", "Hydro Steam"));
        List.add(new Pair("PSYBLADE", "Psyblade"));
        List.add(new Pair("BLOODMOON", "Blood Moon"));
        List.add(new Pair("MATCHAGOTCHA", "Matcha Gotcha"));
        List.add(new Pair("SYRUPBOMB", "Syrup Bomb"));
        List.add(new Pair("IVYCUDGEL", "Ivy Cudgel"));
        List.add(new Pair("ELECTROSHOT", "Electro Shot"));
        List.add(new Pair("TERASTARSTORM", "Tera Starstorm"));
        List.add(new Pair("FICKLEBEAM", "Fickle Beam"));
        List.add(new Pair("BURNINGBULWARK", "Burning Bulwark"));
        List.add(new Pair("THUNDERCLAP", "Thunderclap"));
        List.add(new Pair("MIGHTYCLEAVE", "Mighty Cleave"));
        List.add(new Pair("TACHYONCUTTER", "Tachyon Cutter"));
        List.add(new Pair("HARDPRESS", "Hard Press"));
        List.add(new Pair("DRAGONCHEER", "Dragon Cheer"));
        List.add(new Pair("ALLURINGVOICE", "Alluring Voice"));
        List.add(new Pair("TEMPERFLARE", "Temper Flare"));
        List.add(new Pair("SUPERCELLSLAM", "Supercell Slam"));
        List.add(new Pair("PSYCHICNOISE", "Psychic Noise"));
        List.add(new Pair("UPPERHAND", "Upper Hand"));
        List.add(new Pair("MALIGNANTCHAIN", "Malignant Chain"));
        
        List.add(new Pair("TERABLAST", "Tera Blast"));
    }
}
